/* core/nutritionSupplementCatalog.js — SUP-EVIDENCE-02.
 *
 * Statische, versiebeheerde productcatalogus voor Supplement Evidence
 * & Education. Puur data + accessors -- geen logica die op een vast
 * aantal items is gehardcodeerd. Nieuwe P1/P2/P3-items zijn altijd
 * een extra regel in CATALOG, nooit een enginewijziging (bewust
 * dezelfde filosofie als core/relationship.js VARIABLE_REGISTRY).
 *
 * entity_type onderscheidt vier, nooit-vermengde datatypes
 * (SUP-EVIDENCE-01C sectie 1):
 *   SUBSTANCE        - één scheikundige/biologische stof
 *   INGREDIENT_GROUP  - cluster nauw verwante stoffen, gedeeld contract
 *   PRODUCT_CATEGORY  - commerciële productvorm zonder eigen evidence
 *   RISK_CATEGORY     - cluster dat primair om veiligheids-/
 *                       dopingreden samenhoort, niet om gedeelde werking
 *
 * evidence_coverage_status geeft NIET de wetenschappelijke uitkomst
 * (dat staat in de Evidence Registry) maar uitsluitend of dit item al
 * is doorlopen door het claim-certificeringsproces:
 *   CERTIFIED           - claims voor dit item bestaan in de Evidence
 *                         Registry en zijn production-ready
 *   PENDING_VERIFICATION - catalogitem bestaat, nog geen claims
 *                         gecertificeerd (toekomstige batch)
 *
 * anti_doping_relevance (SUP-EVIDENCE-02A harding) is INTERNE
 * TRIAGE-METADATA, GEEN gecertificeerde WADA-status. Er bestaat op dit
 * moment geen gecertificeerde Supplement Safety / Anti-Doping Registry
 * (bronnen, WADA-lijstjaar, last_verified_at, review_due_at) -- die is
 * expliciet toekomstig werk. Dit veld dient uitsluitend om intern te
 * herkennen welke items later prioriteit verdienen bij het opbouwen
 * van die registry. GEEN enkele laag (EducationService, UI, AI) mag
 * dit veld ooit presenteren als feitelijke dopingstatus. Toegestane
 * waarden (zie ANTI_DOPING_TRIAGE_LEVELS): NONE, REVIEW_REQUIRED,
 * HIGH_RELEVANCE, UNKNOWN. NOT_LISTED/NONE betekent NOOIT
 * "dopingveilig" of "WADA toegestaan" -- uitsluitend "vandaag geen
 * interne triagereden om dit met voorrang te onderzoeken".
 */
(function (root, factory) {
  if (typeof module !== 'undefined' && module.exports) { module.exports = factory(); }
  else { root.NutritionSupplementCatalog = factory(); }
}(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  var CATALOG_VERSION = 'supplement_catalog.v1';
  var ENTITY_TYPES = ['SUBSTANCE', 'INGREDIENT_GROUP', 'PRODUCT_CATEGORY', 'RISK_CATEGORY'];
  var PRIORITIES = ['P0', 'P1', 'P2', 'P3'];
  /* Interne triage-classificatie, GEEN gecertificeerde WADA-status.
   * Zie toelichting hierboven. */
  var ANTI_DOPING_TRIAGE_LEVELS = ['NONE', 'REVIEW_REQUIRED', 'HIGH_RELEVANCE', 'UNKNOWN'];

  /* CATALOG: de daadwerkelijke, actuele telling is altijd CATALOG.length
   * (en de afgeleide byPriority/byEntityType-tellingen hieronder) -- nooit
   * een getal in deze comment. Genormaliseerd uit SUP-EVIDENCE-01B/01C;
   * zie SUP-EVIDENCE-02A-forensisch-rapport voor de volledige,
   * item-voor-item herkomst van elk catalogitem t.o.v. die oorspronkelijke
   * conceptuele lijst. De negen P0-items hebben evidence_coverage_status
   * CERTIFIED (zie nutritionSupplementEvidenceRegistry.js voor hun
   * claims); alle overige items staan als PENDING_VERIFICATION --
   * aanwezig en vindbaar in de catalogus, maar nog zonder gecertificeerde
   * claims (toekomstige Batch B/C/D/E, buiten scope van deze sprint). */
  var CATALOG = [
    // ── P0 ──────────────────────────────────────────────────────────
    { supplement_id: 'CREATINE', canonical_name: 'Creatine', display_name: 'Creatine', synonyms: ['creatinemonohydraat', 'creatine monohydrate'], entity_type: 'SUBSTANCE', categories: ['performance'], priority: 'P0', common_use: 'Kracht/vermogen, herhaalde hoge-intensiteitsinspanning', sport_relevance: 'zeer hoog', safety_relevance: 'aandachtspunt bij bestaande nierziekte', medical_relevance: 'laag (gezonde volwassenen)', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'dose', 'timing', 'safety', 'contraindications'], evidence_coverage_status: 'CERTIFIED' },
    { supplement_id: 'CAFFEINE', canonical_name: 'Caffeine', display_name: 'Cafeïne', synonyms: ['cafeïne', 'koffie', 'coffee'], entity_type: 'SUBSTANCE', categories: ['performance', 'endurance_fuel'], priority: 'P0', common_use: 'Prestatie, alertheid', sport_relevance: 'zeer hoog', safety_relevance: 'dosisafhankelijk, slaapverstoring, zwangerschap', medical_relevance: 'laag-gemiddeld', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'dose', 'timing', 'safety', 'population'], evidence_coverage_status: 'CERTIFIED' },
    { supplement_id: 'BETA_ALANINE', canonical_name: 'Beta-alanine', display_name: 'Bèta-alanine', synonyms: ['β-alanine'], entity_type: 'SUBSTANCE', categories: ['performance'], priority: 'P0', common_use: 'Herhaalde hoge-intensiteitsinspanning 1-10 min', sport_relevance: 'hoog', safety_relevance: 'paresthesie (onschuldig)', medical_relevance: 'zeer laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'dose', 'duration', 'side_effects'], evidence_coverage_status: 'CERTIFIED' },
    { supplement_id: 'PROTEIN_GROUP', canonical_name: 'Protein/whey (groep)', display_name: 'Eiwit', synonyms: ['eiwit', 'whey', 'wei-eiwit', 'proteine'], entity_type: 'INGREDIENT_GROUP', categories: ['protein_muscle'], priority: 'P0', common_use: 'Spiereiwitsynthese, herstel, lichaamssamenstelling', sport_relevance: 'zeer hoog', safety_relevance: 'laag', medical_relevance: 'laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'dose', 'timing', 'population'], evidence_coverage_status: 'CERTIFIED' },
    { supplement_id: 'CARB_GROUP', canonical_name: 'Carbohydrate sports supplements (groep)', display_name: 'Koolhydraten', synonyms: ['koolhydraatgel', 'sportdrank', 'energiegel', 'koolhydraatpoeder'], entity_type: 'INGREDIENT_GROUP', categories: ['endurance_fuel'], priority: 'P0', common_use: 'Brandstof tijdens duurinspanning', sport_relevance: 'zeer hoog', safety_relevance: 'GI-tolerantie', medical_relevance: 'zeer laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'dose', 'duration', 'side_effects'], evidence_coverage_status: 'CERTIFIED' },
    { supplement_id: 'ELECTROLYTE_GROUP', canonical_name: 'Electrolytes/sodium (groep)', display_name: 'Elektrolyten', synonyms: ['elektrolyten', 'natrium', 'sportzout'], entity_type: 'INGREDIENT_GROUP', categories: ['endurance_fuel'], priority: 'P0', common_use: 'Vochtbalans, lange/warme inspanning', sport_relevance: 'hoog', safety_relevance: 'hoog (EAH-context)', medical_relevance: 'gemiddeld (noodgeval-herkenning)', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'safety', 'contraindications', 'medical_referral'], evidence_coverage_status: 'CERTIFIED' },
    { supplement_id: 'VITAMIN_D', canonical_name: 'Vitamin D', display_name: 'Vitamine D', synonyms: ['vitamine D', 'D3', 'cholecalciferol'], entity_type: 'SUBSTANCE', categories: ['micronutrients'], priority: 'P0', common_use: 'Bot/spier/immuunfunctie; disease prevention', sport_relevance: 'hoog (deficiëntierisico)', safety_relevance: 'gemiddeld (toxiciteit bij overdosis)', medical_relevance: 'hoog (diagnose/behandeling apart domein)', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'population', 'medical_referral', 'safety'], evidence_coverage_status: 'CERTIFIED' },
    { supplement_id: 'IRON', canonical_name: 'Iron/ijzer', display_name: 'IJzer', synonyms: ['ijzer', 'ferro', 'ferritine-context'], entity_type: 'SUBSTANCE', categories: ['micronutrients'], priority: 'P0', common_use: 'Zuurstoftransport, vooral relevant bij vrouwelijke sporters', sport_relevance: 'zeer hoog', safety_relevance: 'hoog (toxiciteit, ijzerstapelingsaandoeningen)', medical_relevance: 'zeer hoog (diagnose vereist bloedtest)', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'population', 'medical_referral', 'safety', 'contraindications'], evidence_coverage_status: 'CERTIFIED' },
    { supplement_id: 'MELATONIN', canonical_name: 'Melatonin', display_name: 'Melatonine', synonyms: ['melatonine', 'slaaphormoon'], entity_type: 'SUBSTANCE', categories: ['sleep_stress'], priority: 'P0', common_use: 'Inslaaptijd, jetlag', sport_relevance: 'gemiddeld (herstel/slaapcontext)', safety_relevance: 'gemiddeld (jongeren, regelgeving)', medical_relevance: 'gemiddeld', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'timing', 'side_effects', 'population', 'regulatory'], evidence_coverage_status: 'CERTIFIED' },

    // ── P1 ──────────────────────────────────────────────────────────
    { supplement_id: 'SODIUM_BICARBONATE', canonical_name: 'Sodium bicarbonate', synonyms: ['natriumbicarbonaat', 'baking soda'], entity_type: 'SUBSTANCE', categories: ['performance'], priority: 'P1', common_use: 'Herhaalde hoge-intensiteitsinspanning', sport_relevance: 'hoog', safety_relevance: 'GI-klachten frequent', medical_relevance: 'laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'dose', 'side_effects'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'NITRATE_BEETROOT', canonical_name: 'Dietary nitrate/beetroot juice', synonyms: ['bietensap', 'nitraat'], entity_type: 'SUBSTANCE', categories: ['performance', 'endurance_fuel'], priority: 'P1', common_use: 'Submaximale duurinspanning', sport_relevance: 'hoog', safety_relevance: 'laag', medical_relevance: 'zeer laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'dose', 'timing'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'CITRULLINE', canonical_name: 'Citrulline (malate)', synonyms: ['L-citrulline'], entity_type: 'SUBSTANCE', categories: ['performance'], priority: 'P1', common_use: 'Vermoeidheidsreductie', sport_relevance: 'gemiddeld', safety_relevance: 'laag', medical_relevance: 'zeer laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'dose'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'OMEGA_3', canonical_name: 'Omega-3 (visolie)', synonyms: ['visolie', 'EPA/DHA', 'fish oil'], entity_type: 'SUBSTANCE', categories: ['recovery_health'], priority: 'P1', common_use: 'Herstel/ontsteking', sport_relevance: 'gemiddeld', safety_relevance: 'laag', medical_relevance: 'laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'dose', 'safety'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'EAA', canonical_name: 'Essential amino acids (EAA)', synonyms: ['essentiële aminozuren'], entity_type: 'SUBSTANCE', categories: ['protein_muscle'], priority: 'P1', common_use: 'Spiereiwitsynthese-ondersteuning', sport_relevance: 'gemiddeld', safety_relevance: 'laag', medical_relevance: 'zeer laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'dose'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'BCAA', canonical_name: 'BCAA (los)', synonyms: ['vertakte-keten-aminozuren'], entity_type: 'SUBSTANCE', categories: ['protein_muscle'], priority: 'P1', common_use: 'Vermeend spierherstel', sport_relevance: 'hoog gebruik, laag bewijs', safety_relevance: 'laag', medical_relevance: 'zeer laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'COLLAGEN', canonical_name: 'Collagen/gelatine', synonyms: ['collageen', 'gelatine'], entity_type: 'SUBSTANCE', categories: ['protein_muscle', 'recovery_health'], priority: 'P1', common_use: 'Pees/ligament-context', sport_relevance: 'gemiddeld', safety_relevance: 'laag', medical_relevance: 'zeer laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'sport_context'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'CALCIUM', canonical_name: 'Calcium', synonyms: [], entity_type: 'SUBSTANCE', categories: ['micronutrients'], priority: 'P1', common_use: 'Botgezondheid', sport_relevance: 'gemiddeld', safety_relevance: 'laag', medical_relevance: 'gemiddeld', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'population', 'medical_referral'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'MAGNESIUM', canonical_name: 'Magnesium', synonyms: [], entity_type: 'SUBSTANCE', categories: ['micronutrients', 'sleep_stress'], priority: 'P1', common_use: 'Diverse (performance/slaap, beperkt bewijs)', sport_relevance: 'hoog gebruik', safety_relevance: 'laag', medical_relevance: 'laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'VITAMIN_B12', canonical_name: 'Vitamin B12', synonyms: ['vitamine B12', 'cobalamine'], entity_type: 'SUBSTANCE', categories: ['micronutrients'], priority: 'P1', common_use: 'Relevant bij plantaardig dieet', sport_relevance: 'gemiddeld', safety_relevance: 'laag', medical_relevance: 'gemiddeld', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'population', 'medical_referral'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'MULTIVITAMIN', canonical_name: 'Multivitamins', synonyms: ['multivitamine'], entity_type: 'PRODUCT_CATEGORY', categories: ['micronutrients'], priority: 'P1', common_use: '"Veiligheidsnet" bij adequate voeding', sport_relevance: 'gemiddeld', safety_relevance: 'laag', medical_relevance: 'laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'TART_CHERRY', canonical_name: 'Tart cherry (zure kersen)', synonyms: ['zuurkers'], entity_type: 'SUBSTANCE', categories: ['recovery_health'], priority: 'P1', common_use: 'Spierpijn/herstel', sport_relevance: 'gemiddeld', safety_relevance: 'laag', medical_relevance: 'zeer laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'dose'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'ANTIOXIDANTS_CE', canonical_name: 'Antioxidanten C+E (groep)', synonyms: ['vitamine C+E'], entity_type: 'INGREDIENT_GROUP', categories: ['micronutrients', 'recovery_health'], priority: 'P1', common_use: 'Herstel (mogelijk contraproductief bij hoge dosis rond training)', sport_relevance: 'gemiddeld', safety_relevance: 'laag', medical_relevance: 'laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'limitations'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'THEANINE', canonical_name: 'L-theanine', synonyms: [], entity_type: 'SUBSTANCE', categories: ['sleep_stress'], priority: 'P1', common_use: 'Vaak i.c.m. cafeïne', sport_relevance: 'laag-gemiddeld', safety_relevance: 'laag', medical_relevance: 'zeer laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'ASHWAGANDHA', canonical_name: 'Ashwagandha', synonyms: [], entity_type: 'SUBSTANCE', categories: ['sleep_stress'], priority: 'P1', common_use: 'Stress/slaap (wisselende kwaliteit studies)', sport_relevance: 'gemiddeld', safety_relevance: 'laag-gemiddeld', medical_relevance: 'laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'safety'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'TESTOSTERONE_BOOSTER', canonical_name: 'Testosteron-boosters', synonyms: ['test booster'], entity_type: 'PRODUCT_CATEGORY', categories: ['low_evidence_marketing'], priority: 'P1', common_use: 'Marketingcategorie, geen eigen werkzame stof', sport_relevance: 'hoog gebruik, zeer laag bewijs', safety_relevance: 'gemiddeld-hoog', medical_relevance: 'gemiddeld', anti_doping_relevance: 'REVIEW_REQUIRED', claim_types_required: ['efficacy', 'anti_doping'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'FAT_BURNER', canonical_name: 'Vetverbranders (fat burners)', synonyms: ['fatburner'], entity_type: 'PRODUCT_CATEGORY', categories: ['low_evidence_marketing'], priority: 'P1', common_use: 'Marketingcategorie', sport_relevance: 'hoog gebruik, zeer laag bewijs', safety_relevance: 'hoog (ongedeclareerde stimulantia)', medical_relevance: 'gemiddeld', anti_doping_relevance: 'REVIEW_REQUIRED', claim_types_required: ['efficacy', 'safety'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'DHEA', canonical_name: 'DHEA', synonyms: ['dehydroepiandrosteron'], entity_type: 'SUBSTANCE', categories: ['low_evidence_marketing'], priority: 'P1', common_use: 'Prohormoon', sport_relevance: 'laag', safety_relevance: 'hoog', medical_relevance: 'hoog', anti_doping_relevance: 'HIGH_RELEVANCE', claim_types_required: ['anti_doping', 'medical_referral'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'DMAA', canonical_name: 'DMAA', synonyms: ['1,3-dimethylamylamine', 'methylhexanamine'], entity_type: 'SUBSTANCE', categories: ['low_evidence_marketing'], priority: 'P1', common_use: 'Illegale/high-risk stimulant', sport_relevance: 'n.v.t.', safety_relevance: 'hoog', medical_relevance: 'hoog', anti_doping_relevance: 'HIGH_RELEVANCE', claim_types_required: ['safety', 'anti_doping'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'DMBA', canonical_name: 'DMBA', synonyms: ['1,3-dimethylbutylamine'], entity_type: 'SUBSTANCE', categories: ['low_evidence_marketing'], priority: 'P1', common_use: 'Illegale/high-risk stimulant', sport_relevance: 'n.v.t.', safety_relevance: 'hoog', medical_relevance: 'hoog', anti_doping_relevance: 'HIGH_RELEVANCE', claim_types_required: ['safety', 'anti_doping'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'PROHORMONES', canonical_name: 'Prohormonen (groep)', synonyms: ['androsteendion', 'norandrosteendion'], entity_type: 'RISK_CATEGORY', categories: ['low_evidence_marketing'], priority: 'P1', common_use: 'n.v.t.', sport_relevance: 'n.v.t.', safety_relevance: 'hoog', medical_relevance: 'hoog', anti_doping_relevance: 'HIGH_RELEVANCE', claim_types_required: ['anti_doping', 'medical_referral'], evidence_coverage_status: 'PENDING_VERIFICATION' },

    // ── P2 (verkort weergegeven per categorie) ─────────────────────
    { supplement_id: 'SODIUM_PHOSPHATE', canonical_name: 'Sodium phosphate', synonyms: [], entity_type: 'SUBSTANCE', categories: ['performance'], priority: 'P2', common_use: 'Beperkt onderzocht ergogeen', sport_relevance: 'laag', safety_relevance: 'laag', medical_relevance: 'zeer laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'ARGININE', canonical_name: 'Arginine', synonyms: ['L-arginine'], entity_type: 'SUBSTANCE', categories: ['performance'], priority: 'P2', common_use: 'Vermeend NO-effect', sport_relevance: 'laag', safety_relevance: 'laag', medical_relevance: 'zeer laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'TAURINE', canonical_name: 'Taurine', synonyms: [], entity_type: 'SUBSTANCE', categories: ['performance', 'endurance_fuel'], priority: 'P2', common_use: 'Vaak in energiedranken', sport_relevance: 'laag', safety_relevance: 'laag', medical_relevance: 'zeer laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'BETAINE', canonical_name: 'Betaine', synonyms: ['trimethylglycine'], entity_type: 'SUBSTANCE', categories: ['performance'], priority: 'P2', common_use: 'Kleine, wisselende studies', sport_relevance: 'laag', safety_relevance: 'laag', medical_relevance: 'zeer laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'HMB', canonical_name: 'HMB', synonyms: ['β-hydroxy β-methylbutyraat'], entity_type: 'SUBSTANCE', categories: ['performance', 'protein_muscle'], priority: 'P2', common_use: 'Wisselend bewijs bij getrainden', sport_relevance: 'laag-gemiddeld', safety_relevance: 'laag', medical_relevance: 'zeer laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'population'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'CARNITINE', canonical_name: 'Carnitine', synonyms: ['L-carnitine'], entity_type: 'SUBSTANCE', categories: ['performance'], priority: 'P2', common_use: 'Vetstofwisseling (beperkt effect)', sport_relevance: 'laag-gemiddeld', safety_relevance: 'laag', medical_relevance: 'zeer laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'KETONE_ESTERS', canonical_name: 'Ketone esters', synonyms: ['ketonen'], entity_type: 'SUBSTANCE', categories: ['performance', 'endurance_fuel'], priority: 'P2', common_use: 'Nichetoepassing', sport_relevance: 'laag-gemiddeld', safety_relevance: 'GI-klachten', medical_relevance: 'zeer laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'safety'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'RIBOSE', canonical_name: 'Ribose', synonyms: ['D-ribose'], entity_type: 'SUBSTANCE', categories: ['performance'], priority: 'P2', common_use: 'Klinisch/medisch onderzocht, niet sport', sport_relevance: 'zeer laag', safety_relevance: 'laag', medical_relevance: 'laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'COQ10', canonical_name: 'CoQ10', synonyms: ['coenzym Q10'], entity_type: 'SUBSTANCE', categories: ['performance', 'recovery_health'], priority: 'P2', common_use: 'Vooral cardiovasculair onderzocht', sport_relevance: 'zeer laag', safety_relevance: 'laag', medical_relevance: 'laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'AGMATINE', canonical_name: 'Agmatine', synonyms: [], entity_type: 'SUBSTANCE', categories: ['performance'], priority: 'P2', common_use: 'Populair in pre-workouts, weinig menselijk bewijs', sport_relevance: 'laag', safety_relevance: 'laag', medical_relevance: 'zeer laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'LEUCINE', canonical_name: 'Leucine (los)', synonyms: [], entity_type: 'SUBSTANCE', categories: ['protein_muscle'], priority: 'P2', common_use: 'Mechanistisch relevant, praktisch beperkt boven volwaardig eiwit', sport_relevance: 'gemiddeld', safety_relevance: 'laag', medical_relevance: 'zeer laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'GLUTAMINE', canonical_name: 'Glutamine', synonyms: ['L-glutamine'], entity_type: 'SUBSTANCE', categories: ['protein_muscle'], priority: 'P2', common_use: 'Weinig overtuigend sport-specifiek bewijs', sport_relevance: 'laag', safety_relevance: 'laag', medical_relevance: 'zeer laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'MASS_GAINER', canonical_name: 'Mass gainers', synonyms: ['weight gainer'], entity_type: 'PRODUCT_CATEGORY', categories: ['protein_muscle'], priority: 'P2', common_use: 'Calorie-eiwitpoeder', sport_relevance: 'gemiddeld', safety_relevance: 'laag', medical_relevance: 'zeer laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'PLANT_PROTEIN', canonical_name: 'Plantaardig eiwit (soja/erwt/ei-alternatief)', synonyms: ['soja-eiwit', 'erwteneiwit'], entity_type: 'SUBSTANCE', categories: ['protein_muscle'], priority: 'P2', common_use: 'Allergie/veganistisch alternatief', sport_relevance: 'gemiddeld', safety_relevance: 'laag', medical_relevance: 'laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'population'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'MTC_OIL', canonical_name: 'MCT-olie', synonyms: ['medium-chain triglycerides'], entity_type: 'SUBSTANCE', categories: ['endurance_fuel'], priority: 'P2', common_use: 'Nichetoepassing', sport_relevance: 'laag-gemiddeld', safety_relevance: 'GI-klachten', medical_relevance: 'zeer laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'safety'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'ZINC', canonical_name: 'Zink', synonyms: [], entity_type: 'SUBSTANCE', categories: ['micronutrients'], priority: 'P2', common_use: 'Relevant bij restrictief eten/veganisme', sport_relevance: 'laag-gemiddeld', safety_relevance: 'laag', medical_relevance: 'gemiddeld', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'population', 'medical_referral'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'FOLATE', canonical_name: 'Folate/foliumzuur', synonyms: ['vitamine B9'], entity_type: 'SUBSTANCE', categories: ['micronutrients'], priority: 'P2', common_use: 'Zwangerschapscontext', sport_relevance: 'laag', safety_relevance: 'laag', medical_relevance: 'hoog (zwangerschap)', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'population', 'medical_referral'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'VITAMIN_C', canonical_name: 'Vitamin C', synonyms: ['vitamine C', 'ascorbinezuur'], entity_type: 'SUBSTANCE', categories: ['micronutrients'], priority: 'P2', common_use: 'Antioxidant-context', sport_relevance: 'gemiddeld', safety_relevance: 'laag', medical_relevance: 'laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'limitations'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'VITAMIN_E', canonical_name: 'Vitamin E', synonyms: ['vitamine E'], entity_type: 'SUBSTANCE', categories: ['micronutrients'], priority: 'P2', common_use: 'Antioxidant-context', sport_relevance: 'laag', safety_relevance: 'laag', medical_relevance: 'laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'IODINE', canonical_name: 'Jodium', synonyms: ['jood'], entity_type: 'SUBSTANCE', categories: ['micronutrients'], priority: 'P2', common_use: 'Minder vaak relevant', sport_relevance: 'laag', safety_relevance: 'laag', medical_relevance: 'gemiddeld', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'medical_referral'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'PROBIOTICS', canonical_name: 'Probiotica', synonyms: [], entity_type: 'SUBSTANCE', categories: ['recovery_health'], priority: 'P2', common_use: 'Immuun/GI-context, stam-specifiek', sport_relevance: 'gemiddeld', safety_relevance: 'laag', medical_relevance: 'laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'limitations'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'CURCUMIN', canonical_name: 'Curcumine (kurkuma)', synonyms: ['turmeric'], entity_type: 'SUBSTANCE', categories: ['recovery_health'], priority: 'P2', common_use: 'Anti-inflammatoir', sport_relevance: 'gemiddeld', safety_relevance: 'interactie met biobeschikbaarheid/bloedverdunners', medical_relevance: 'laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'interactions'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'NAC', canonical_name: 'N-acetylcysteïne', synonyms: ['NAC'], entity_type: 'SUBSTANCE', categories: ['recovery_health'], priority: 'P2', common_use: 'Antioxidant-context', sport_relevance: 'laag', safety_relevance: 'laag', medical_relevance: 'laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'RHODIOLA', canonical_name: 'Rhodiola', synonyms: ['rhodiola rosea'], entity_type: 'SUBSTANCE', categories: ['sleep_stress'], priority: 'P2', common_use: 'Stress-adaptogeen, beperkt bewijs', sport_relevance: 'laag-gemiddeld', safety_relevance: 'laag', medical_relevance: 'laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'FRUIT_POLYPHENOLS', canonical_name: 'Fruit-polyfenolen (groep)', synonyms: ['bessen', 'blackcurrant', 'granaatappel'], entity_type: 'INGREDIENT_GROUP', categories: ['recovery_health'], priority: 'P2', common_use: 'Herstel/antioxidant-context', sport_relevance: 'gemiddeld', safety_relevance: 'laag', medical_relevance: 'zeer laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },

    // ── P3 ──────────────────────────────────────────────────────────
    { supplement_id: 'GLYCEROL', canonical_name: 'Glycerol', synonyms: [], entity_type: 'SUBSTANCE', categories: ['performance', 'endurance_fuel'], priority: 'P3', common_use: 'Vochtretentie in hitte', sport_relevance: 'laag-gemiddeld', safety_relevance: 'laag', medical_relevance: 'zeer laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy', 'sport_context'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'GINSENG', canonical_name: 'Ginseng', synonyms: [], entity_type: 'SUBSTANCE', categories: ['sleep_stress', 'low_evidence_marketing'], priority: 'P3', common_use: 'Adaptogeen, weinig sportbewijs', sport_relevance: 'laag', safety_relevance: 'laag', medical_relevance: 'laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'GLYCINE', canonical_name: 'Glycine', synonyms: [], entity_type: 'SUBSTANCE', categories: ['sleep_stress'], priority: 'P3', common_use: 'Slaapcontext, beperkt bewijs', sport_relevance: 'laag', safety_relevance: 'laag', medical_relevance: 'zeer laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'GLUCOSAMINE', canonical_name: 'Glucosamine', synonyms: [], entity_type: 'SUBSTANCE', categories: ['low_evidence_marketing'], priority: 'P3', common_use: 'Gewrichtscontext', sport_relevance: 'laag', safety_relevance: 'laag', medical_relevance: 'laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'CHROMIUM_PICOLINATE', canonical_name: 'Chromium picolinate', synonyms: ['chroompicolinaat'], entity_type: 'SUBSTANCE', categories: ['low_evidence_marketing'], priority: 'P3', common_use: 'Vermeend bloedsuiker/vetverliescontext', sport_relevance: 'zeer laag', safety_relevance: 'laag', medical_relevance: 'laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'OXYGENATED_WATER', canonical_name: 'Oxygenated waters', synonyms: ['zuurstofwater'], entity_type: 'PRODUCT_CATEGORY', categories: ['low_evidence_marketing'], priority: 'P3', common_use: 'Marketingproduct', sport_relevance: 'zeer laag', safety_relevance: 'laag', medical_relevance: 'zeer laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'ZMA', canonical_name: 'ZMA', synonyms: ['zink-magnesium-B6'], entity_type: 'PRODUCT_CATEGORY', categories: ['low_evidence_marketing'], priority: 'P3', common_use: 'Vermeend testosteron/slaapcontext', sport_relevance: 'laag', safety_relevance: 'laag', medical_relevance: 'laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'INOSINE', canonical_name: 'Inosine', synonyms: [], entity_type: 'SUBSTANCE', categories: ['low_evidence_marketing'], priority: 'P3', common_use: 'Verouderd vermeend ergogeen', sport_relevance: 'zeer laag', safety_relevance: 'laag', medical_relevance: 'laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'PYRUVATE', canonical_name: 'Pyruvate', synonyms: [], entity_type: 'SUBSTANCE', categories: ['low_evidence_marketing'], priority: 'P3', common_use: 'Verouderd vermeend vetverliesmiddel', sport_relevance: 'zeer laag', safety_relevance: 'laag', medical_relevance: 'laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'CLA', canonical_name: 'CLA (geconjugeerd linolzuur)', synonyms: ['conjugated linoleic acid'], entity_type: 'SUBSTANCE', categories: ['low_evidence_marketing'], priority: 'P3', common_use: 'Weerlegd vetverliesmiddel', sport_relevance: 'zeer laag', safety_relevance: 'laag', medical_relevance: 'laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'DAA', canonical_name: 'D-aspartaat (DAA)', synonyms: ['D-aspartic acid'], entity_type: 'SUBSTANCE', categories: ['low_evidence_marketing'], priority: 'P3', common_use: 'Vaak in testosteron-boosters', sport_relevance: 'laag', safety_relevance: 'laag-gemiddeld', medical_relevance: 'laag', anti_doping_relevance: 'REVIEW_REQUIRED', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'MACA', canonical_name: 'Maca-wortel', synonyms: ['maca root'], entity_type: 'SUBSTANCE', categories: ['low_evidence_marketing'], priority: 'P3', common_use: 'Vermeend energie/libido-context', sport_relevance: 'laag', safety_relevance: 'laag', medical_relevance: 'laag', anti_doping_relevance: 'REVIEW_REQUIRED', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },

    // ── Overige PRODUCT_CATEGORY/RISK_CATEGORY-items (tijdens implementatie
    //    aanvullend geidentificeerd t.o.v. de oorspronkelijke 01B/01C-lijst;
    //    zie SUP-EVIDENCE-02A-forensisch-rapport voor de herkomst per item) ──
    { supplement_id: 'PREWORKOUT_BLEND', canonical_name: 'Pre-workout blends', synonyms: ['pre-workout'], entity_type: 'PRODUCT_CATEGORY', categories: ['blends'], priority: 'P2', common_use: 'Erft nooit automatisch de evidence van zijn ingrediënten', sport_relevance: 'zeer hoog gebruik', safety_relevance: 'afhankelijk van ingrediënten', medical_relevance: 'afhankelijk van ingrediënten', anti_doping_relevance: 'UNKNOWN', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'DETOX_PRODUCT', canonical_name: 'Detox-producten', synonyms: [], entity_type: 'PRODUCT_CATEGORY', categories: ['low_evidence_marketing'], priority: 'P2', common_use: 'Fysiologisch ongefundeerd', sport_relevance: 'zeer laag', safety_relevance: 'laag', medical_relevance: 'laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'GREENS_POWDER', canonical_name: 'Greens/"superfood"-poeders', synonyms: ['greens'], entity_type: 'PRODUCT_CATEGORY', categories: ['low_evidence_marketing'], priority: 'P2', common_use: 'Geen bewezen gelijkwaardigheid aan hele voeding', sport_relevance: 'gemiddeld gebruik', safety_relevance: 'laag', medical_relevance: 'laag', anti_doping_relevance: 'NONE', claim_types_required: ['efficacy'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'STIMULANT_ADULTERANTS', canonical_name: 'Stimulant-adulterants (groep)', synonyms: ['ephedrine-achtigen'], entity_type: 'RISK_CATEGORY', categories: ['low_evidence_marketing'], priority: 'P1', common_use: 'n.v.t.', sport_relevance: 'n.v.t.', safety_relevance: 'hoog', medical_relevance: 'hoog', anti_doping_relevance: 'HIGH_RELEVANCE', claim_types_required: ['safety', 'anti_doping'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'BETA2_AGONISTS', canonical_name: 'Beta-2-agonisten (groep)', synonyms: [], entity_type: 'RISK_CATEGORY', categories: ['low_evidence_marketing'], priority: 'P2', common_use: 'n.v.t.', sport_relevance: 'n.v.t.', safety_relevance: 'hoog', medical_relevance: 'hoog', anti_doping_relevance: 'HIGH_RELEVANCE', claim_types_required: ['safety', 'anti_doping'], evidence_coverage_status: 'PENDING_VERIFICATION' },
    { supplement_id: 'UNDECLARED_CONTAMINATION', canonical_name: 'Ongedeclareerde verontreiniging (algemeen)', synonyms: ['product contamination'], entity_type: 'RISK_CATEGORY', categories: ['low_evidence_marketing'], priority: 'P1', common_use: 'Generieke veiligheidsuitleg, geen productadvies', sport_relevance: 'n.v.t.', safety_relevance: 'hoog', medical_relevance: 'laag', anti_doping_relevance: 'HIGH_RELEVANCE', claim_types_required: ['safety', 'anti_doping'], evidence_coverage_status: 'PENDING_VERIFICATION' }
  ];

  function isValidEntityType(t) { return ENTITY_TYPES.indexOf(t) >= 0; }
  function isValidPriority(p) { return PRIORITIES.indexOf(p) >= 0; }
  function isValidAntiDopingTriage(t) { return ANTI_DOPING_TRIAGE_LEVELS.indexOf(t) >= 0; }
  /* getDisplayName: SUP-EVIDENCE-03B presentatielaag. display_name is
   * UITSLUITEND presentatie -- wijzigt nooit supplement_id/canonical_name,
   * bevat geen claims/evidence, en breekt nooit synonym-matching (die
   * blijft via bySynonymOrName op canonical_name + display_name +
   * synonyms lopen). Items zonder display_name vallen terug op
   * canonical_name, dus deze functie is altijd veilig aan te roepen. */
  function getDisplayName(item) { return (item && (item.display_name || item.canonical_name)) || ''; }

  function allItems() { return CATALOG.slice(); }
  function getById(id) {
    for (var i = 0; i < CATALOG.length; i++) if (CATALOG[i].supplement_id === id) return CATALOG[i];
    return null;
  }
  function byEntityType(type) { return CATALOG.filter(function (i) { return i.entity_type === type; }); }
  function byPriority(p) { return CATALOG.filter(function (i) { return i.priority === p; }); }
  function bySynonymOrName(query) {
    if (!query) return null;
    var q = String(query).trim().toLowerCase();
    for (var i = 0; i < CATALOG.length; i++) {
      var item = CATALOG[i];
      if (item.canonical_name.toLowerCase() === q) return item;
      if (item.display_name && item.display_name.toLowerCase() === q) return item;
      if ((item.synonyms || []).some(function (s) { return s.toLowerCase() === q; })) return item;
    }
    return null;
  }

  var NutritionSupplementCatalog = {
    CATALOG_VERSION: CATALOG_VERSION,
    ENTITY_TYPES: ENTITY_TYPES,
    PRIORITIES: PRIORITIES,
    ANTI_DOPING_TRIAGE_LEVELS: ANTI_DOPING_TRIAGE_LEVELS,
    CATALOG: CATALOG,
    isValidEntityType: isValidEntityType,
    isValidPriority: isValidPriority,
    isValidAntiDopingTriage: isValidAntiDopingTriage,
    getDisplayName: getDisplayName,
    allItems: allItems,
    getById: getById,
    byEntityType: byEntityType,
    byPriority: byPriority,
    bySynonymOrName: bySynonymOrName
  };

  return NutritionSupplementCatalog;
}));
