/* core/nutritionSupplementSourceRegistry.js — SUP-EVIDENCE-02.
 *
 * Concrete, traceerbare bronrecords voor de Supplement Evidence
 * Registry. Geen enkele claim mag verwijzen naar een niet-bestaande
 * source_id; dat wordt afgedwongen door
 * fSupplementEvidenceRegistry.test.js. Elke bron is een echt,
 * opzoekbaar document (DOI of officiële URL) -- geen verzonnen bron.
 */
(function (root, factory) {
  if (typeof module !== 'undefined' && module.exports) { module.exports = factory(); }
  else { root.NutritionSupplementSourceRegistry = factory(); }
}(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  var REGISTRY_VERSION = 'supplement_source_registry.v1';
  var SOURCE_STATUSES = ['CURRENT', 'CURRENT_BUT_SCOPE_LIMITED', 'CURRENT_BUT_UNDER_REVIEW', 'SUPERSEDED', 'OUT_OF_SCOPE', 'INSUFFICIENT'];

  var SOURCES = [
    { source_id: 'ISSN-CREATINE-2017', title: 'ISSN position stand: safety and efficacy of creatine supplementation in exercise, sport, and medicine', authors_or_organisation: 'Kreider RB, Kalman DS, Antonio J, et al. (International Society of Sports Nutrition)', publication_date: '2017-06-13', source_type: 'position_stand', doi: '10.1186/s12970-017-0173-z', official_url: 'https://doi.org/10.1186/s12970-017-0173-z', source_status: 'CURRENT', last_verified_at: '2026-09-07' },
    { source_id: 'CRE-KIDNEY-METAANALYSE-2025', title: 'Effect of creatine supplementation on kidney function: a systematic review and meta-analysis', authors_or_organisation: 'Naeini EK, Eskandari M, Mortazavi M, Gholaminejad A, Karevan N', publication_date: '2025-11-06', source_type: 'systematic_review', doi: '10.1186/s12882-025-04558-6', official_url: 'https://doi.org/10.1186/s12882-025-04558-6', source_status: 'CURRENT', last_verified_at: '2026-09-07' },
    { source_id: 'CRE-KIDNEY-METAANALYSE-2026', title: 'Impact of creatine supplementation on kidney health: a systematic review and meta-analysis', authors_or_organisation: 'International Urology and Nephrology (auteurs zie publicatie)', publication_date: '2026-01-01', source_type: 'systematic_review', doi: '10.1007/s11255-026-05287-x', official_url: 'https://doi.org/10.1007/s11255-026-05287-x', source_status: 'CURRENT', last_verified_at: '2026-09-07' },
    { source_id: 'KDIGO-CKD-2024', title: 'KDIGO 2024 Clinical Practice Guideline for the Evaluation and Management of Chronic Kidney Disease', authors_or_organisation: 'Kidney Disease: Improving Global Outcomes (KDIGO)', publication_date: '2024-01-01', source_type: 'clinical_guideline', doi: '10.1016/j.kint.2023.10.018', official_url: 'https://doi.org/10.1016/j.kint.2023.10.018', source_status: 'CURRENT', last_verified_at: '2026-09-07' },
    { source_id: 'ISSN-CAFFEINE-2021', title: 'International society of sports nutrition position stand: caffeine and exercise performance', authors_or_organisation: 'Guest NS, VanDusseldorp TA, Nelson MT, et al. (ISSN)', publication_date: '2021-01-02', source_type: 'position_stand', doi: '10.1186/s12970-020-00383-4', official_url: 'https://doi.org/10.1186/s12970-020-00383-4', source_status: 'CURRENT', last_verified_at: '2026-09-07' },
    { source_id: 'EFSA-CAFFEINE-2015', title: 'Scientific Opinion on the safety of caffeine', authors_or_organisation: 'EFSA Panel on Dietetic Products, Nutrition and Allergies (NDA)', publication_date: '2015-05-27', source_type: 'regulatory_opinion', doi: '10.2903/j.efsa.2015.4102', official_url: 'https://doi.org/10.2903/j.efsa.2015.4102', source_status: 'CURRENT_BUT_UNDER_REVIEW', last_verified_at: '2026-09-07' },
    { source_id: 'ISSN-BETAALANINE-2015', title: 'International society of sports nutrition position stand: Beta-Alanine', authors_or_organisation: 'Trexler ET, Smith-Ryan AE, Stout JR, et al. (ISSN)', publication_date: '2015-07-15', source_type: 'position_stand', doi: '10.1186/s12970-015-0090-y', official_url: 'https://doi.org/10.1186/s12970-015-0090-y', source_status: 'CURRENT', last_verified_at: '2026-09-07' },
    { source_id: 'BA-METAANALYSE-IJSNEM-2024', title: 'Effect of Beta-Alanine Supplementation on Maximal Intensity Exercise in Trained Young Male Individuals: A Systematic Review and Meta-Analysis', authors_or_organisation: 'International Journal of Sport Nutrition and Exercise Metabolism, Vol 34(6)', publication_date: '2024-07-19', source_type: 'systematic_review', doi: null, official_url: 'https://journals.humankinetics.com/view/journals/ijsnem/34/6/article-p397.xml', source_status: 'CURRENT', last_verified_at: '2026-09-07' },
    { source_id: 'BA-HOBSON-METAANALYSE-2012', title: 'Effects of β-alanine supplementation on exercise performance: a meta-analysis', authors_or_organisation: 'Hobson RM, Saunders B, Ball G, Harris RC, Sale C', publication_date: '2012-01-24', source_type: 'meta_analysis', doi: '10.1007/s00726-011-1200-z', official_url: 'https://doi.org/10.1007/s00726-011-1200-z', source_status: 'CURRENT', last_verified_at: '2026-09-07' },
    { source_id: 'ISSN-PROTEIN-2017', title: 'International Society of Sports Nutrition Position Stand: protein and exercise', authors_or_organisation: 'Jäger R, Kerksick CM, Campbell BI, et al. (ISSN)', publication_date: '2017-06-20', source_type: 'position_stand', doi: '10.1186/s12970-017-0177-8', official_url: 'https://doi.org/10.1186/s12970-017-0177-8', source_status: 'CURRENT', last_verified_at: '2026-09-07' },
    { source_id: 'ISSN-NUTRIENT-TIMING-2017', title: 'International society of sports nutrition position stand: nutrient timing', authors_or_organisation: 'Kerksick CM, Arent S, Schoenfeld BJ, et al. (ISSN)', publication_date: '2017-08-29', source_type: 'position_stand', doi: '10.1186/s12970-017-0189-4', official_url: 'https://doi.org/10.1186/s12970-017-0189-4', source_status: 'CURRENT', last_verified_at: '2026-09-07' },
    { source_id: 'ACSM-FLUID-REPLACEMENT-2007', title: 'American College of Sports Medicine position stand. Exercise and fluid replacement', authors_or_organisation: 'Sawka MN, Burke LM, Eichner ER, Maughan RJ, Montain SJ, Stachenfeld NS (ACSM)', publication_date: '2007-02-01', source_type: 'position_stand', doi: '10.1249/mss.0b013e31802ca597', official_url: 'https://doi.org/10.1249/mss.0b013e31802ca597', source_status: 'CURRENT_BUT_SCOPE_LIMITED', last_verified_at: '2026-09-07' },
    // ── NK-06: micronutriënten (Calcium/Magnesium/Zink/B12/Folaat/Jodium) ──
    { source_id: 'EFSA-DRV-TOPIC-OVERVIEW', title: 'Dietary reference values (topic overview, incl. Scientific Opinions on DRVs for calcium, magnesium, zinc, folate, vitamin B12, iodine)', authors_or_organisation: 'EFSA Panel on Nutrition, Novel Foods and Food Allergens (NDA)', publication_date: '2024-08-05', source_type: 'official_reference_values', doi: null, official_url: 'https://www.efsa.europa.eu/en/topics/topic/dietary-reference-values', source_status: 'CURRENT', last_verified_at: '2026-09-07' },
    { source_id: 'COCHRANE-MAGNESIUM-CRAMPS-2020', title: 'Magnesium for skeletal muscle cramps', authors_or_organisation: 'Garrison SR, Korownyk CS, Kolber MR, Allan GM, Musini VM, Sekhon RK, Dugré N', publication_date: '2020-09-21', source_type: 'systematic_review', doi: '10.1002/14651858.CD009402.pub3', official_url: 'https://www.cochranelibrary.com/cdsr/doi/10.1002/14651858.CD009402.pub3/full', source_status: 'CURRENT', last_verified_at: '2026-09-07' },
    { source_id: 'MTE-ATHLETIC-PERFORMANCE-SYSREV-2019', title: 'The Role of Mineral and Trace Element Supplementation in Exercise and Athletic Performance: A Systematic Review', authors_or_organisation: 'Heffernan SM, Horner K, De Vito G, Conway GE', publication_date: '2019-03-24', source_type: 'systematic_review', doi: '10.3390/nu11030696', official_url: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6471179/', source_status: 'CURRENT', last_verified_at: '2026-09-07' },
    // ── NK-07: Supplement Knowledge Completion (resterende P1-items) ──
    { source_id: 'ISSN-REVIEW-2018', title: 'ISSN exercise & sports nutrition review update: research & recommendations', authors_or_organisation: 'Kerksick CM, Wilborn CD, Roberts MD, Smith-Ryan A, Kleiner SM, Jäger R, et al. (ISSN)', publication_date: '2018-08-01', source_type: 'position_stand', doi: '10.1186/s12970-018-0242-y', official_url: 'https://doi.org/10.1186/s12970-018-0242-y', source_status: 'CURRENT', last_verified_at: '2026-09-08' },
    { source_id: 'ISSN-BICARBONATE-2021', title: 'International Society of Sports Nutrition position stand: sodium bicarbonate and exercise performance', authors_or_organisation: 'Grgic J, Pedisic Z, Saunders B, Artioli GG, Schoenfeld BJ, et al. (ISSN)', publication_date: '2021-09-09', source_type: 'position_stand', doi: '10.1186/s12970-021-00458-w', official_url: 'https://doi.org/10.1186/s12970-021-00458-w', source_status: 'CURRENT', last_verified_at: '2026-09-08' },
    { source_id: 'NITRATE-PERFORMANCE-JONES-2014', title: 'Dietary nitrate supplementation and exercise performance', authors_or_organisation: 'Jones AM', publication_date: '2014-05-01', source_type: 'review', doi: '10.1007/s40279-014-0149-y', official_url: 'https://doi.org/10.1007/s40279-014-0149-y', source_status: 'CURRENT_BUT_SCOPE_LIMITED', last_verified_at: '2026-09-08' },
    { source_id: 'TARTCHERRY-META-2026', title: 'Effects of Tart Cherry Juice Supplementation on Recovery from Exercise-Induced Muscle Damage in Athletes: A Systematic Review and Meta-Analysis', authors_or_organisation: 'Daab W, Bouzid MA, Nassis GP, Arumugam A, Ammar A, Pojskić H, Abaïdia AE', publication_date: '2026-04-07', source_type: 'systematic_review', doi: '10.1186/s40798-026-00993-3', official_url: 'https://pubmed.ncbi.nlm.nih.gov/41945263/', source_status: 'CURRENT', last_verified_at: '2026-09-08' },
    { source_id: 'FDA-DMAA-DMBA-SAFETY', title: 'DMAA and DMBA in Products Marketed as Dietary Supplements (consumer safety communications)', authors_or_organisation: 'U.S. Food and Drug Administration (FDA)', publication_date: '2015-04-01', source_type: 'regulatory_notice', doi: null, official_url: 'https://www.opss.org/article/dmaa-prohibited-stimulant', source_status: 'CURRENT', last_verified_at: '2026-09-08' },
    { source_id: 'WADA-PROHIBITED-LIST-CURRENT', title: 'The Prohibited List (S1 Anabolic Agents, S6 Stimulants)', authors_or_organisation: 'World Anti-Doping Agency (WADA)', publication_date: '2026-01-01', source_type: 'regulatory_notice', doi: null, official_url: 'https://www.wada-ama.org/en/prohibited-list', source_status: 'CURRENT', last_verified_at: '2026-09-08' },
    { source_id: 'CARB-DURING-EXERCISE-JEUKENDRUP-2014', title: 'A Step Towards Personalized Sports Nutrition: Carbohydrate Intake During Exercise', authors_or_organisation: 'Jeukendrup AE', publication_date: '2014-05-03', source_type: 'review', doi: '10.1007/s40279-014-0148-z', official_url: 'https://doi.org/10.1007/s40279-014-0148-z', source_status: 'CURRENT', last_verified_at: '2026-09-07' },
    { source_id: 'ENDOCRINE-SOCIETY-VITD-2024', title: 'Vitamin D for the Prevention of Disease: An Endocrine Society Clinical Practice Guideline', authors_or_organisation: 'Demay MB, et al. (Endocrine Society)', publication_date: '2024-06-24', source_type: 'clinical_guideline', doi: null, official_url: 'https://www.endocrine.org/clinical-practice-guidelines/vitamin-d-for-prevention-of-disease', source_status: 'CURRENT_BUT_SCOPE_LIMITED', last_verified_at: '2026-09-07' },
    { source_id: 'VITD-CRITICAL-APPRAISAL-2026', title: 'The 2024 Endocrine Society Guideline on Vitamin D: Comprehensive Summary and Critical Appraisal', authors_or_organisation: 'MDPI Nutrients (auteurs zie publicatie)', publication_date: '2026-05-05', source_type: 'critical_appraisal', doi: null, official_url: 'https://www.mdpi.com/2072-6643/18/9/1472', source_status: 'CURRENT', last_verified_at: '2026-09-07' },
    { source_id: 'VITD-PERF-SIST-2023', title: 'Effects of vitamin D supplementation on maximal strength and power in athletes: a systematic review and meta-analysis of randomized controlled trials', authors_or_organisation: 'Sist M, Zou L, Galloway SDR, Rodriguez-Sanchez N', publication_date: '2023-09-29', source_type: 'systematic_review', doi: '10.3389/fnut.2023.1163313', official_url: 'https://doi.org/10.3389/fnut.2023.1163313', source_status: 'INSUFFICIENT', last_verified_at: '2026-09-07' },
    { source_id: 'VITD-PERF-HAN-2024', title: 'Effects of vitamin D3 supplementation on strength of lower and upper extremities in athletes: an updated systematic review and meta-analysis of randomized controlled trials', authors_or_organisation: 'Han Q, Xiang M, An N, Tan Q, Shao J, Wang Q', publication_date: '2024-05-27', source_type: 'systematic_review', doi: '10.3389/fnut.2024.1381301', official_url: 'https://doi.org/10.3389/fnut.2024.1381301', source_status: 'INSUFFICIENT', last_verified_at: '2026-09-07' },
    { source_id: 'IOC-REDS-CONSENSUS-2023', title: "2023 International Olympic Committee's (IOC) consensus statement on Relative Energy Deficiency in Sport (REDs)", authors_or_organisation: 'Mountjoy M, Ackerman KE, Bailey DM, et al. (IOC)', publication_date: '2023-01-01', source_type: 'consensus_statement', doi: null, official_url: 'https://bjsm.bmj.com/content/57/17/1073', source_status: 'CURRENT', last_verified_at: '2026-09-07' },
    { source_id: 'IRON-FEMALE-ATHLETES-PENGELLY-2025', title: 'Iron deficiency, supplementation, and sports performance in female athletes: A systematic review', authors_or_organisation: 'Pengelly M, Pumpa K, Pyne DB, Etxebarria N', publication_date: '2025-12-01', source_type: 'systematic_review', doi: '10.1016/j.jshs.2024.101009', official_url: 'https://doi.org/10.1016/j.jshs.2024.101009', source_status: 'CURRENT', last_verified_at: '2026-09-07' },
    { source_id: 'RVS-MELATONINE-2026', title: 'Uitspraak 202201857/1/A3 en 202201863/1/A3 (ECLI:NL:RVS:2026:1846)', authors_or_organisation: 'Afdeling bestuursrechtspraak van de Raad van State', publication_date: '2026-04-01', source_type: 'court_ruling', doi: null, official_url: 'https://www.raadvanstate.nl/uitspraken/@157371/202201857-1-a3-en-202201863-1-a3/', source_status: 'CURRENT', last_verified_at: '2026-09-07' },
    { source_id: 'RVS-MELATONINE-2022-VOORLOPIG', title: 'Uitspraak 202201857/2/A3 en 202201863/2/A3 (ECLI:NL:RVS:2022:3934)', authors_or_organisation: 'Afdeling bestuursrechtspraak van de Raad van State (voorzieningenrechter)', publication_date: '2022-12-22', source_type: 'court_ruling', doi: null, official_url: 'https://www.raadvanstate.nl/uitspraken/@134628/202201857-2-a3-en-202201863-2-a3/', source_status: 'CURRENT', last_verified_at: '2026-09-07' },
    { source_id: 'NPN-MELATONINE-FACTSHEET-2017', title: 'Factsheet melatonine', authors_or_organisation: 'Natuur- en Gezondheidsproducten Nederland (NPN), o.b.v. EFSA-gezondheidsclaims', publication_date: '2017-04-01', source_type: 'industry_factsheet_citing_efsa', doi: null, official_url: 'https://www.npninfo.nl/wp-content/uploads/images/Factsheet%20melatonine.pdf', source_status: 'CURRENT', last_verified_at: '2026-09-07' },
    { source_id: 'KAMERVRAGEN-MELATONINE-2019', title: 'Kamervragen (Aanhangsel) 2019-2020, nr. 297 — melatoninegebruik jongeren', authors_or_organisation: 'Tweede Kamer der Staten-Generaal / Minister van VWS', publication_date: '2019-10-31', source_type: 'parliamentary_record', doi: null, official_url: 'https://zoek.officielebekendmakingen.nl/ah-tk-20192020-297.html', source_status: 'CURRENT', last_verified_at: '2026-09-07' }
  ];

  function isValidStatus(s) { return SOURCE_STATUSES.indexOf(s) >= 0; }
  function allSources() { return SOURCES.slice(); }
  function getById(id) {
    for (var i = 0; i < SOURCES.length; i++) if (SOURCES[i].source_id === id) return SOURCES[i];
    return null;
  }

  var NutritionSupplementSourceRegistry = {
    REGISTRY_VERSION: REGISTRY_VERSION,
    SOURCE_STATUSES: SOURCE_STATUSES,
    SOURCES: SOURCES,
    isValidStatus: isValidStatus,
    allSources: allSources,
    getById: getById
  };

  return NutritionSupplementSourceRegistry;
}));
