/* core/nutritionKnowledgeEvidenceRegistry.js — NK-01.
 *
 * NIEUWE claims voor de Nutrition Knowledge & Evidence Platform --
 * uitsluitend content die nog niet gecertificeerd bestaat in
 * nutritionSupplementEvidenceRegistry.js. Sport-specifieke creatine-
 * en eiwitclaims (prestatie, dosering, timing, veiligheid) blijven
 * daar staan en worden door nutritionKnowledgeService.js via
 * cross-reference opgehaald -- NOOIT hier gedupliceerd met een
 * afwijkende formulering.
 *
 * Zelfde vocabulaire als de Supplement Evidence Registry (bewust GEEN
 * tweede, conflicterende schaal): evidence_level A-E,
 * status VERIFIED/INSUFFICIENT/REVISE/REMOVE.
 */
(function (root, factory) {
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = factory(require('./nutritionKnowledgeSources.js'));
  } else {
    root.NutritionKnowledgeEvidenceRegistry = factory(root.NutritionKnowledgeSources);
  }
}(typeof self !== 'undefined' ? self : this, function (KnowledgeSources) {
  'use strict';

  var REGISTRY_VERSION = 'nutrition_knowledge_evidence_registry.v1';
  var EVIDENCE_LEVELS = ['A', 'B', 'C', 'D', 'E'];
  var STATUSES = ['VERIFIED', 'INSUFFICIENT', 'REVISE', 'REMOVE'];

  var CLAIMS = [
    // ── CREATINE (nieuw, niet in Supplement Evidence Registry) ─────────
    { claim_id: 'NK-CRE-DEF-001', topic_id: 'CREATINE', domain: 'SUPPLEMENT', claim_text_internal: 'Creatine is een van nature in het lichaam voorkomende stof, gesynthetiseerd uit de aminozuren arginine, glycine en methionine (lever, nieren, pancreas), en wordt daarnaast via voeding (rood vlees, vis) binnengekregen. Circa 95% wordt opgeslagen in skeletspier.', user_friendly_summary: 'Creatine is geen kunstmatige of vreemde stof: je lichaam maakt het zelf, en het zit ook in vlees en vis. Het grootste deel wordt opgeslagen in je spieren.', evidence_level: 'A', population: 'algemeen', context: 'achtergrond/fysiologie', supported_outcomes: ['basiskennis'], limitations: [], source_ids: ['ISSN-CREATINE-2017'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['creatine is een kunstmatige/synthetische drug', 'creatine is een anabole steroïde'] },
    { claim_id: 'NK-CRE-MECH-001', topic_id: 'CREATINE', domain: 'SUPPLEMENT', claim_text_internal: 'Creatine wordt in spierweefsel omgezet naar fosfocreatine, dat dient als snel beschikbare energiebuffer voor de resynthese van ATP tijdens korte, zeer intensieve inspanning.', user_friendly_summary: 'In je spieren helpt creatine je lichaam om supersnel energie bij te vullen tijdens korte, zware inspanningen zoals sprinten of een zware herhaling.', evidence_level: 'A', population: 'algemeen', context: 'fysiologisch mechanisme', supported_outcomes: ['basiskennis'], limitations: [], source_ids: ['ISSN-CREATINE-2017'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: [] },
    { claim_id: 'NK-CRE-CYCLE-001', topic_id: 'CREATINE', domain: 'SUPPLEMENT', claim_text_internal: 'Er is geen wetenschappelijk bewijs dat cyclen (periodiek stoppen en herstarten) van creatinegebruik noodzakelijk of voordelig is; continu gebruik op de aanbevolen dosis is veilig en effectief op lange termijn.', user_friendly_summary: 'Je hoeft creatine niet af te wisselen met stopperiodes ("cyclen") -- continu gebruik werkt net zo goed en is niet minder veilig.', evidence_level: 'A', population: 'gezonde volwassenen', context: 'gebruikspatroon', supported_outcomes: ['geen noodzaak tot cyclen'], limitations: [], source_ids: ['ISSN-CREATINE-2017'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['cyclen is noodzakelijk voor effectiviteit', 'je lichaam went aan creatine waardoor het stopt met werken'] },
    { claim_id: 'NK-CRE-WEIGHT-001', topic_id: 'CREATINE', domain: 'SUPPLEMENT', claim_text_internal: 'Initiële gewichtstoename bij aanvang van creatinegebruik is vrijwel volledig toe te schrijven aan intracellulair watervasthouden (een normaal, osmotisch effect van het natrium-afhankelijke creatinetransport in de spiercel), niet aan vetopslag. Latere, blijvende gewichtsveranderingen komen primair van trainingsgedreven spiermassatoename.', user_friendly_summary: 'Merk je dat je iets zwaarder wordt als je met creatine begint? Dat is vooral extra water in je spieren, geen vet. Blijvende gewichtstoename op langere termijn komt van spiergroei door training.', evidence_level: 'B', population: 'algemeen', context: 'gewichtseffect', supported_outcomes: ['duiding van vroege gewichtstoename'], limitations: ['individuele variatie in de mate van watertoename'], source_ids: ['ISSN-CREATINE-2017'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['creatine laat je vet aankomen', 'gewichtstoename door creatine is altijd blijvend en ongewenst'] },
    { claim_id: 'NK-CRE-MISC-001', topic_id: 'CREATINE', domain: 'SUPPLEMENT', claim_text_internal: 'Creatine is geen anabole steroïde en geen hormoon; het is een van nature voorkomend, niet-hormonaal stikstofhoudend molecuul.', user_friendly_summary: 'Creatine wordt soms verward met doping of hormonen, maar dat is het niet -- het is een gewone, natuurlijke voedingsstof.', evidence_level: 'A', population: 'algemeen', context: 'veelgemaakt misverstand', supported_outcomes: ['correctie van een veelvoorkomend misverstand'], limitations: [], source_ids: ['ISSN-CREATINE-2017'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['creatine is een vorm van doping', 'creatine is een hormoonpreparaat'] },

    // ── EIWITTEN (nieuw, algemene voedingskennis) ──────────────────────
    { claim_id: 'NK-PROT-DEF-001', topic_id: 'PROTEIN', domain: 'NUTRITION', claim_text_internal: 'Eiwit (proteïne) is een macronutriënt opgebouwd uit ketens van aminozuren; het is een structurele bouwstof (o.a. spieren, huid, enzymen, hormonen, antilichamen).', user_friendly_summary: 'Eiwit is een van de drie hoofdvoedingsstoffen (naast koolhydraten en vet) en bestaat uit bouwstenen die aminozuren heten. Je lichaam gebruikt eiwit voor van alles: van spieren tot je afweersysteem.', evidence_level: 'A', population: 'algemeen', context: 'achtergrond/definitie', supported_outcomes: ['basiskennis'], limitations: [], source_ids: ['WHO-FAO-UNU-PROTEIN-2007'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: [] },
    { claim_id: 'NK-PROT-AA-001', topic_id: 'PROTEIN', domain: 'NUTRITION', claim_text_internal: 'Van de circa 20 aminozuren die eiwitten opbouwen, zijn er 9 essentieel: het lichaam kan ze niet zelf aanmaken en ze moeten via voeding worden verkregen.', user_friendly_summary: 'Er zijn 9 "essentiële" aminozuren die je alleen via voeding binnenkrijgt -- je lichaam kan ze niet zelf maken.', evidence_level: 'A', population: 'algemeen', context: 'achtergrond/definitie', supported_outcomes: ['basiskennis'], limitations: [], source_ids: ['WHO-FAO-UNU-PROTEIN-2007'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: [] },
    { claim_id: 'NK-PROT-RDA-001', topic_id: 'PROTEIN', domain: 'NUTRITION', claim_text_internal: 'Voor de algemene, niet-sportende volwassen bevolking geldt een gemiddelde eiwitbehoefte van circa 0,66 g/kg/dag en een "veilig niveau" (RDA-equivalent) van circa 0,83 g/kg/dag, gebaseerd op stikstofbalansonderzoek.', user_friendly_summary: 'Voor de gemiddelde, niet-sportende volwassene ligt de aanbevolen eiwitinname rond 0,8 g per kg lichaamsgewicht per dag -- sporters hebben vaak meer nodig (zie de sportgerichte secties hieronder).', evidence_level: 'A', population: 'algemene, niet-sportende volwassenen', context: 'algemene voedingsbehoefte, GEEN sportcontext', supported_outcomes: ['stikstofbalans/onderhoud'], limitations: ['geldt niet voor sporters -- zie PROT-TOTAL-001 voor de sportgerichte 1,4-2,0 g/kg-range'], source_ids: ['WHO-FAO-UNU-PROTEIN-2007'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['0,8 g/kg is ook voor sporters voldoende', 'de algemene RDA en de sportrichtlijn zijn hetzelfde getal'] },
    { claim_id: 'NK-PROT-QUALITY-001', topic_id: 'PROTEIN', domain: 'NUTRITION', claim_text_internal: 'Eiwitkwaliteit wordt o.a. bepaald met de Digestible Indispensable Amino Acid Score (DIAAS), die aminozuursamenstelling en verteerbaarheid combineert. Dierlijke eiwitbronnen (vlees, ei, wei, caseïne) scoren als individueel voedingsmiddel doorgaans hoger dan de meeste individuele plantaardige bronnen.', user_friendly_summary: 'Niet alle eiwit is precies gelijkwaardig: dierlijke eiwitbronnen scoren op zichzelf vaak iets hoger op erkende kwaliteitsmaten dan losse plantaardige bronnen.', evidence_level: 'A', population: 'algemeen', context: 'eiwitkwaliteit', supported_outcomes: ['begrip van eiwitkwaliteitverschillen'], limitations: ['DIAAS meet individuele voedingsmiddelen; complete maaltijden/diëten complementeren elkaar (zie NK-PROT-PLANT-001)'], source_ids: ['DIAAS-HERREMAN-2020'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['plantaardig eiwit is waardeloos', 'alleen dierlijk eiwit telt mee'] },
    { claim_id: 'NK-PROT-PLANT-001', topic_id: 'PROTEIN', domain: 'NUTRITION', claim_text_internal: 'Combinatie van verschillende plantaardige eiwitbronnen (bv. peulvruchten met granen) over de dag verhoogt de gecombineerde aminozuurkwaliteit tot een niveau vergelijkbaar met dierlijke bronnen; combineren in exact dezelfde maaltijd is daarvoor niet vereist.', user_friendly_summary: 'Eet je vooral plantaardig? Door verschillende plantaardige eiwitbronnen over de dag te verspreiden (bv. peulvruchten en granen), vul je elkaars aminozuren goed aan -- dat hoeft niet per se in één maaltijd.', evidence_level: 'B', population: 'algemeen, met name plantaardig etende mensen', context: 'eiwitkwaliteit/vegetarisch-veganistisch', supported_outcomes: ['complementaire eiwitstrategie'], limitations: [], source_ids: ['DIAAS-HERREMAN-2020'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['je moet elke maaltijd complementaire eiwitten combineren'] },
    { claim_id: 'NK-PROT-VEGAN-001', topic_id: 'PROTEIN', domain: 'NUTRITION', claim_text_internal: 'Bij een overwegend of volledig plantaardig voedingspatroon kan een enigszins hogere totale eiwitinname en aandacht voor voldoende variatie in eiwitbronnen aangewezen zijn, om eventuele lagere individuele eiwitkwaliteit te compenseren.', user_friendly_summary: 'Eet je vegetarisch of veganistisch? Let dan op voldoende variatie en eventueel een iets hogere totale eiwitinname om kwaliteitsverschillen te compenseren.', evidence_level: 'C', population: 'vegetariërs/veganisten', context: 'vegetarisch/veganistisch', supported_outcomes: ['aandachtspunt bij plantaardig voedingspatroon'], limitations: ['contextafhankelijk, geen vaste extra hoeveelheid gecertificeerd'], source_ids: ['DIAAS-HERREMAN-2020', 'WHO-FAO-UNU-PROTEIN-2007'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['plantaardig eten betekent automatisch een eiwittekort'] },

    // ── KOOLHYDRATEN (NK-03, nieuw) ─────────────────────────────────────
    { claim_id: 'NK-CARB-DEF-001', topic_id: 'CARBOHYDRATES', domain: 'NUTRITION', claim_text_internal: 'Koolhydraten zijn een macronutriënt die door het lichaam wordt afgebroken tot glucose; overtollige glucose wordt opgeslagen als glycogeen in spieren en lever.', user_friendly_summary: 'Koolhydraten worden in je lichaam omgezet in glucose (bloedsuiker). Wat je niet meteen verbruikt, sla je op als glycogeen in spieren en lever.', evidence_level: 'A', population: 'algemeen', context: 'achtergrond/definitie', supported_outcomes: ['basiskennis'], limitations: [], source_ids: ['WHO-CARBOHYDRATE-2023'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: [] },
    { claim_id: 'NK-CARB-QUALITY-001', topic_id: 'CARBOHYDRATES', domain: 'NUTRITION', claim_text_internal: 'WHO beveelt aan dat koolhydraatinname primair afkomstig is van volkoren granen, groente, fruit en peulvruchten, in plaats van een eenvoudige indeling in "simpel" versus "complex".', user_friendly_summary: 'Voor koolhydraatkwaliteit gaat het vooral om de bron: volkoren, groente, fruit en peulvruchten zijn de aanbevolen basis -- meer dan het onderscheid "simpel" versus "complex".', evidence_level: 'A', population: 'algemeen, 2 jaar en ouder', context: 'koolhydraatkwaliteit', supported_outcomes: ['voedingskeuze'], limitations: [], source_ids: ['WHO-CARBOHYDRATE-2023'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: [] },
    { claim_id: 'NK-CARB-GI-001', topic_id: 'CARBOHYDRATES', domain: 'NUTRITION', claim_text_internal: 'De glykemische index/load is een bruikbaar, maar op zichzelf onvoldoende criterium voor koolhydraatkwaliteit; WHO geeft de voorkeur aan richtlijnen op basis van voedingsmiddelbron en vezelgehalte.', user_friendly_summary: 'De glykemische index kan nuttig zijn, maar zegt niet het hele verhaal over of een koolhydraatbron "goed" of "slecht" is -- de bron en vezels tellen minstens zo zwaar mee.', evidence_level: 'B', population: 'algemeen', context: 'koolhydraatkwaliteit', supported_outcomes: ['juiste duiding van GI/GL'], limitations: ['geen consensus over GI/GL als enige of beste indicator'], source_ids: ['WHO-CARBOHYDRATE-2023'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['lage GI = altijd gezonder', 'hoge GI = altijd ongezond'] },
    { claim_id: 'NK-CARB-SUGAR-001', topic_id: 'CARBOHYDRATES', domain: 'NUTRITION', claim_text_internal: 'WHO adviseert de inname van vrije suikers te beperken tot minder dan 10% van de totale energie-inname, met een verdere, voorwaardelijke aanbeveling tot onder 5% voor aanvullende gezondheidsvoordelen.', user_friendly_summary: 'Beperk toegevoegde/vrije suikers tot minder dan 10% van je totale energie-inname; onder 5% geeft mogelijk extra voordeel.', evidence_level: 'A', population: 'algemeen', context: 'vrije/toegevoegde suikers', supported_outcomes: ['tandcariës-preventie', 'gewichtsbeheersing'], limitations: ['de 5%-aanbeveling is voorwaardelijk, gebaseerd op zwakker bewijs dan de 10%-aanbeveling'], source_ids: ['WHO-SUGARS-2015'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['suiker is gif', 'alle suiker moet vermeden worden'] },
    { claim_id: 'NK-CARB-LOWCARB-001', topic_id: 'CARBOHYDRATES', domain: 'NUTRITION', claim_text_internal: 'Systematisch literatuuronderzoek toont geen overtuigend verschil in gewichtsverlies of cardiovasculaire risicofactoren tussen low-carb-diëten en calorie-gematchte, uitgebalanceerde diëten op de langere termijn (1-2 jaar); op de korte termijn (3-6 maanden) kan low-carb iets sneller gewichtsverlies geven.', user_friendly_summary: 'Low-carb-diëten geven vaak sneller resultaat op de korte termijn, maar op de langere termijn (1-2 jaar) is er geen overtuigend verschil met een gewone, calorie-gecontroleerde, uitgebalanceerde manier van eten.', evidence_level: 'A', population: 'volwassenen met overgewicht/obesitas', context: 'vetverlies/dieetvergelijking', supported_outcomes: ['gewichtsverlies op lange termijn'], limitations: ['vooral onderzocht bij mensen met overgewicht/obesitas, niet specifiek bij lean sporters'], source_ids: ['NAUDE-LOWCARB-META-2014'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['low-carb is bewezen beter voor vetverlies dan andere diëten'] },
    { claim_id: 'NK-CARB-NOTUNHEALTHY-001', topic_id: 'CARBOHYDRATES', domain: 'NUTRITION', claim_text_internal: 'Koolhydraten zijn niet inherent ongezond of "dikmakend"; gewichtstoename hangt samen met de totale energiebalans, en koolhydraatkwaliteit (volkoren/vezelrijk versus sterk bewerkt/vrije suikers) is relevanter dan de macronutriëntcategorie op zich.', user_friendly_summary: 'Koolhydraten zelf maken je niet dik -- dat hangt af van je totale energiebalans. Wél maakt het uit wélke koolhydraten je vooral eet: volkoren en vezelrijk versus sterk bewerkt en veel vrije suikers.', evidence_level: 'A', population: 'algemeen', context: 'veelgemaakt misverstand', supported_outcomes: ['correctie van een veelvoorkomend misverstand'], limitations: [], source_ids: ['WHO-CARBOHYDRATE-2023', 'WHO-HEALTHY-DIET-2020'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['koolhydraten maken dik', 'alle koolhydraten zijn ongezond'] },

    // ── VETTEN (NK-03, nieuw) ────────────────────────────────────────────
    { claim_id: 'NK-FAT-DEF-001', topic_id: 'FATS', domain: 'NUTRITION', claim_text_internal: 'Voedingsvetten zijn een energiedichte macronutriënt (circa 9 kcal/g); essentiële vetzuren (linolzuur, alfa-linoleenzuur) kan het lichaam niet zelf aanmaken en moeten via voeding worden verkregen.', user_friendly_summary: 'Vet levert meer energie per gram dan eiwit of koolhydraten. Sommige vetzuren zijn "essentieel" -- die kan je lichaam niet zelf maken, dus die moeten uit voeding komen.', evidence_level: 'A', population: 'algemeen', context: 'achtergrond/definitie', supported_outcomes: ['basiskennis'], limitations: [], source_ids: ['WHO-TOTALFAT-2023'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: [] },
    { claim_id: 'NK-FAT-INTAKE-001', topic_id: 'FATS', domain: 'NUTRITION', claim_text_internal: 'WHO adviseert een totale vetinname van minimaal 15-20% van de totale energie-inname (voor essentiële vetzuren en vitamineopname) en maximaal circa 30% ter voorkoming van ongezonde gewichtstoename.', user_friendly_summary: 'Vet mag niet te weinig (minimaal 15-20% van je energie-inname) maar ook niet te veel zijn (doorgaans niet meer dan zo\'n 30%).', evidence_level: 'A', population: 'volwassenen', context: 'totale vetinname', supported_outcomes: ['gewichtsbeheersing', 'essentiële-vetzurenvoorziening'], limitations: [], source_ids: ['WHO-TOTALFAT-2023'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['vet moet zoveel mogelijk vermeden worden'] },
    { claim_id: 'NK-FAT-TYPES-001', topic_id: 'FATS', domain: 'NUTRITION', claim_text_internal: 'WHO adviseert verzadigd vet te beperken tot minder dan 10% en transvet tot minder dan 1% van de totale energie-inname, en deze te vervangen door onverzadigde vetzuren.', user_friendly_summary: 'Beperk verzadigd vet (minder dan 10% van je energie-inname) en transvet (minder dan 1%), en vervang deze bij voorkeur door onverzadigde vetten.', evidence_level: 'A', population: 'algemeen, 2 jaar en ouder', context: 'vetkwaliteit', supported_outcomes: ['cardiovasculaire gezondheid'], limitations: [], source_ids: ['WHO-SFA-TFA-2023'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['verzadigd vet is precies hetzelfde als onverzadigd vet'] },
    { claim_id: 'NK-FAT-VITAMINS-001', topic_id: 'FATS', domain: 'NUTRITION', claim_text_internal: 'Voldoende vetinname is nodig voor de opname van de vetoplosbare vitamines A, D, E en K.', user_friendly_summary: 'Vet helpt je lichaam om de vitamines A, D, E en K goed op te nemen -- daarom is vet volledig vermijden niet verstandig.', evidence_level: 'A', population: 'algemeen', context: 'vitamineopname', supported_outcomes: ['vitamineopname'], limitations: [], source_ids: ['WHO-TOTALFAT-2023'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: [] },
    { claim_id: 'NK-FAT-BODYFAT-001', topic_id: 'FATS', domain: 'NUTRITION', claim_text_internal: 'Voedingsvet wordt niet automatisch lichaamsvet; de totale energiebalans (inname versus verbruik) bepaalt of er vetopslag optreedt, ongeacht welk macronutriënt de overtollige energie levert.', user_friendly_summary: 'Vet eten betekent niet automatisch vet aankomen -- dat hangt af van je totale energiebalans, niet alleen van welk voedingsmiddel de calorieën levert.', evidence_level: 'C', population: 'algemeen', context: 'energiebalans/lichaamssamenstelling', supported_outcomes: ['correcte duiding van vetopslag'], limitations: ['vereenvoudigde weergave; verzadiging/hormonale effecten per macronutriënt verschillen enigszins, maar veranderen het basisprincipe niet'], source_ids: ['FAO-WHO-UNU-ENERGY-2004'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['vet eten is hetzelfde als vet aankomen', 'vet is de enige oorzaak van gewichtstoename'] },
    { claim_id: 'NK-FAT-NOTBAD-001', topic_id: 'FATS', domain: 'NUTRITION', claim_text_internal: 'Vet is niet inherent ongezond; het type vet (verzadigd/transvet versus onverzadigd) en de context van het totale voedingspatroon bepalen de gezondheidsimpact, niet vet als categorie op zich.', user_friendly_summary: 'Vet is niet per definitie "slecht" -- het type vet en je totale voedingspatroon maken het verschil, niet vet als categorie.', evidence_level: 'A', population: 'algemeen', context: 'veelgemaakt misverstand', supported_outcomes: ['correctie van een veelvoorkomend misverstand'], limitations: [], source_ids: ['WHO-SFA-TFA-2023'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['vet is ongezond', 'alle vetten zijn hetzelfde'] },

    // ── ENERGIE (NK-03, nieuw) ───────────────────────────────────────────
    { claim_id: 'NK-ENE-DEF-001', topic_id: 'ENERGY', domain: 'NUTRITION', claim_text_internal: 'Energie uit voeding wordt uitgedrukt in kilocalorieën (kcal) of kilojoules (kJ, 1 kcal ≈ 4,184 kJ); koolhydraten en eiwit leveren circa 4 kcal/g, vet circa 9 kcal/g, alcohol circa 7 kcal/g.', user_friendly_summary: 'Energie in voeding wordt gemeten in kcal (calorieën) of kJ. Vet levert per gram meer dan twee keer zoveel energie als eiwit of koolhydraten.', evidence_level: 'A', population: 'algemeen', context: 'achtergrond/definitie', supported_outcomes: ['basiskennis'], limitations: [], source_ids: ['FAO-WHO-UNU-ENERGY-2004'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: [] },
    { claim_id: 'NK-ENE-BALANCE-001', topic_id: 'ENERGY', domain: 'NUTRITION', claim_text_internal: 'Energiebalans is de verhouding tussen energie-inname (voeding) en energieverbruik (basaal metabolisme, activiteit, voedselvertering); een aanhoudend overschot of tekort leidt over tijd tot gewichtsverandering.', user_friendly_summary: 'Energiebalans is simpelweg: wat je binnenkrijgt versus wat je verbruikt. Een langdurig overschot of tekort verandert je gewicht.', evidence_level: 'A', population: 'algemeen', context: 'achtergrond/definitie', supported_outcomes: ['basiskennis'], limitations: [], source_ids: ['FAO-WHO-UNU-ENERGY-2004'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: [] },
    { claim_id: 'NK-ENE-BMR-001', topic_id: 'ENERGY', domain: 'NUTRITION', claim_text_internal: 'BMR (basaal metabolisme) is de energie die het lichaam in rust verbruikt voor levensessentiële functies; TDEE (totaal dagelijks energieverbruik) is BMR vermeerderd met energie voor activiteit en voedselvertering. Dit zijn educatieve concepten -- Trainingskompas berekent hier geen persoonlijke BMR/TDEE-waarde mee uit.', user_friendly_summary: 'BMR is de energie die je lichaam in rust verbruikt; TDEE is je totale dagverbruik (BMR + activiteit + vertering). Dit zijn begrippen om te begrijpen, geen rekentool.', evidence_level: 'A', population: 'algemeen', context: 'achtergrond/definitie', supported_outcomes: ['basiskennis'], limitations: ['individuele BMR/TDEE-schattingen kennen aanzienlijke onzekerheidsmarges'], source_ids: ['FAO-WHO-UNU-ENERGY-2004'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['Trainingskompas berekent jouw BMR/TDEE', 'BMR-formules zijn exact'] },
    { claim_id: 'NK-ENE-REDS-001', topic_id: 'ENERGY', domain: 'NUTRITION', claim_text_internal: 'Lage energiebeschikbaarheid (te weinig voedingsenergie t.o.v. het energieverbruik van training, na aftrek van de energiekosten van dagelijkse activiteiten) kan leiden tot Relative Energy Deficiency in Sport (RED-S), met mogelijke gevolgen voor hormonale functie, botgezondheid, immuunfunctie en prestatie.', user_friendly_summary: 'Als je structureel te weinig energie binnenkrijgt voor wat je lichaam nodig heeft (inclusief training), kan dat leiden tot RED-S -- met mogelijke gevolgen voor hormonen, botten, afweer en prestatie.', evidence_level: 'A', population: 'sporters, met name bij hoog trainingsvolume of bewuste restrictie', context: 'RED-S/lage energiebeschikbaarheid', supported_outcomes: ['herkenning van risicofactoren'], limitations: ['diagnose en behandeling van RED-S vereisen medische/sportmedische beoordeling'], source_ids: ['IOC-REDS-CONSENSUS-2023'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['Trainingskompas diagnosticeert RED-S', 'RED-S betekent automatisch dat je een eetstoornis hebt'] },
    { claim_id: 'NK-ENE-WEARABLE-001', topic_id: 'ENERGY', domain: 'NUTRITION', claim_text_internal: 'Validatiestudies tonen dat polsdraagbare consumententrackers de energie-uitgave tijdens inspanning met aanzienlijke foutmarges schatten (in onderzoek doorgaans circa 15-30% gemiddelde absolute afwijking, oplopend per activiteit/device).', user_friendly_summary: 'De calorieën die je smartwatch tijdens het sporten toont, zijn een schatting met een aanzienlijke foutmarge (vaak 15-30% of meer) -- geen exacte meting.', evidence_level: 'A', population: 'algemeen', context: 'wearable-nauwkeurigheid', supported_outcomes: ['juiste duiding van wearable-data'], limitations: ['foutmarge varieert sterk per device en activiteitstype'], source_ids: ['SHCHERBINA-WEARABLE-2017'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['wearable-calorieën zijn exact', 'Trainingskompas kan de wearable-foutmarge corrigeren tot een exact getal'] },
    { claim_id: 'NK-ENE-NOCALC-001', topic_id: 'ENERGY', domain: 'NUTRITION', claim_text_internal: 'Trainingskompas berekent geen persoonlijke calorie-, macro- of energiebehoefte-doelen (geen BMR-formule, geen TDEE-formule, geen gewicht x factor); dit is architectuurbeleid, geen gebruikerszin.', user_friendly_summary: null, evidence_level: 'E', population: null, context: null, supported_outcomes: [], limitations: [], source_ids: [], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: false, forbidden_interpretations: ['AI berekent jouw persoonlijke calorieBehoefte', 'AI berekent jouw macrodoelen'] },

    // ── VEZELS (NK-03, nieuw) ────────────────────────────────────────────
    { claim_id: 'NK-FIB-DEF-001', topic_id: 'FIBRE', domain: 'NUTRITION', claim_text_internal: 'Voedingsvezels zijn niet-verteerbare koolhydraten uit plantaardige voeding; ze worden onderverdeeld in oplosbare en onoplosbare vezels, met elk verschillende effecten op spijsvertering en gezondheid.', user_friendly_summary: 'Vezels zijn niet-verteerbare koolhydraten uit plantaardige voeding. Er zijn oplosbare en onoplosbare vezels, die elk net iets anders doen in je spijsvertering.', evidence_level: 'A', population: 'algemeen', context: 'achtergrond/definitie', supported_outcomes: ['basiskennis'], limitations: [], source_ids: ['WHO-CARBOHYDRATE-2023'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: [] },
    { claim_id: 'NK-FIB-INTAKE-001', topic_id: 'FIBRE', domain: 'NUTRITION', claim_text_internal: 'WHO adviseert volwassenen minimaal 25 g natuurlijk voorkomende voedingsvezels per dag, verkregen uit voeding (niet uit supplementen).', user_friendly_summary: 'Streef als volwassene naar minstens 25 gram vezels per dag, niet primair uit supplementen maar uit voeding zelf.', evidence_level: 'A', population: 'volwassenen', context: 'aanbevolen inname', supported_outcomes: ['algemene gezondheid'], limitations: [], source_ids: ['WHO-CARBOHYDRATE-2023'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: [] },
    { claim_id: 'NK-FIB-HEALTH-001', topic_id: 'FIBRE', domain: 'NUTRITION', claim_text_internal: 'Een hogere inname van voedingsvezels, volkoren granen, groente, fruit en peulvruchten is geassocieerd met een verlaagd risico op het ontwikkelen van/overlijden aan hart- en vaatziekten, diabetes type 2 en bepaalde vormen van kanker.', user_friendly_summary: 'Meer vezels, volkoren, groente, fruit en peulvruchten hangen samen met een lager risico op hart- en vaatziekten, diabetes type 2 en bepaalde kankers.', evidence_level: 'A', population: 'algemeen', context: 'gezondheidseffecten', supported_outcomes: ['risicoreductie chronische ziekte'], limitations: ['grotendeels observationeel onderzoek, aanvullend ondersteund door RCT\'s op tussentijdse uitkomstmaten'], source_ids: ['WHO-CARBOHYDRATE-2023'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['vezels genezen hart- en vaatziekten', 'vezels voorkomen kanker met zekerheid'] },
    { claim_id: 'NK-FIB-SATIETY-001', topic_id: 'FIBRE', domain: 'NUTRITION', claim_text_internal: 'Een hogere vezelinname is geassocieerd met kleine reducties in maten van lichaamsvet, mogelijk deels via een verzadigingseffect; dit is geen gegarandeerd of op zichzelf staand middel voor gewichtsverlies.', user_friendly_summary: 'Vezels kunnen een beetje helpen bij verzadiging en lichaamssamenstelling, maar zijn geen garantie voor gewichtsverlies op zich.', evidence_level: 'B', population: 'algemeen', context: 'verzadiging/lichaamssamenstelling', supported_outcomes: ['ondersteuning bij verzadiging'], limitations: ['effect is klein, geen op zichzelf staande vetverliesstrategie'], source_ids: ['WHO-CARBOHYDRATE-2023'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['vezels zorgen gegarandeerd voor gewichtsverlies'] },
    { claim_id: 'NK-FIB-SUPPLEMENT-001', topic_id: 'FIBRE', domain: 'NUTRITION', claim_text_internal: 'Vezelsupplementen leveren geïsoleerde vezel, maar niet automatisch dezelfde volledige voordelen als vezelrijke hele voeding, die ook andere gunstige stoffen (o.a. fytochemicaliën) bevat.', user_friendly_summary: 'Een vezelsupplement is niet automatisch hetzelfde als vezelrijke, volledige voeding -- die laatste bevat ook andere waardevolle stoffen.', evidence_level: 'B', population: 'algemeen', context: 'supplement versus voeding', supported_outcomes: ['juiste verwachting van vezelsupplementen'], limitations: [], source_ids: ['WHO-CARBOHYDRATE-2023'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['een vezelsupplement is precies hetzelfde als vezelrijke voeding'] },
    { claim_id: 'NK-FIB-GI-001', topic_id: 'FIBRE', domain: 'NUTRITION', claim_text_internal: 'Een plotselinge hoge vezelinname, met name vlak vóór training of wedstrijd, kan bij individueel gevoelige personen maag-darmklachten veroorzaken; geleidelijk verhogen van de vezelinname en voldoende vochtinname worden algemeen aanbevolen om dit te beperken.', user_friendly_summary: 'Veel vezels vlak vóór het sporten kan bij sommige mensen buikklachten geven. Vezelinname geleidelijk opbouwen en genoeg drinken helpt dit te beperken.', evidence_level: 'C', population: 'algemeen, met name sporters rond training/wedstrijd', context: 'sportcontext/GI-tolerantie', supported_outcomes: ['praktisch advies GI-tolerantie'], limitations: ['individuele tolerantie varieert sterk, geen vaste drempelwaarde gecertificeerd'], source_ids: ['WHO-CARBOHYDRATE-2023'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['vezels vlak voor training zijn voor iedereen gevaarlijk'] },

    // ── GEZONDE VOEDING (NK-03, nieuw) ───────────────────────────────────
    { claim_id: 'NK-HE-PATTERN-001', topic_id: 'HEALTHY_EATING', domain: 'NUTRITION', claim_text_internal: 'Een gezond voedingspatroon wordt bepaald door de samenstelling van het geheel over tijd (variatie, verhouding groente/fruit/volkoren/peulvruchten/eiwitbronnen/vetkwaliteit/beperkte vrije suikers en zout), niet door één product op zich.', user_friendly_summary: 'Gezonde voeding gaat over je totale patroon over tijd -- niet over of één product op zich "goed" of "slecht" is.', evidence_level: 'A', population: 'algemeen', context: 'algemene gezondheidsrichtlijn', supported_outcomes: ['begrip van voedingspatroon boven eenmalig product'], limitations: [], source_ids: ['WHO-HEALTHY-DIET-2020'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['één ongezonde maaltijd verpest je hele voedingspatroon', 'één "superfood" maakt je voeding gezond'] },
    { claim_id: 'NK-HE-FRUITVEG-001', topic_id: 'HEALTHY_EATING', domain: 'NUTRITION', claim_text_internal: 'WHO adviseert minimaal 400 g groente en fruit per dag (exclusief aardappelen/zetmeelrijke knollen) als onderdeel van een gezond voedingspatroon.', user_friendly_summary: 'Streef naar minstens 400 gram groente en fruit per dag (aardappelen tellen hier niet bij).', evidence_level: 'A', population: 'algemeen', context: 'algemene gezondheidsrichtlijn', supported_outcomes: ['risicoreductie chronische ziekte', 'vezelinname'], limitations: [], source_ids: ['WHO-HEALTHY-DIET-2020'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: [] },
    { claim_id: 'NK-HE-PROCESSED-001', topic_id: 'HEALTHY_EATING', domain: 'NUTRITION', claim_text_internal: '"Bewerkte voeding" is geen eenduidig, universeel wetenschappelijk gedefinieerde categorie die per definitie ongezond is; relevanter voor gezondheidsrichtlijnen is het gehalte aan verzadigd vet, transvet, vrije suikers en zout/natrium in het product.', user_friendly_summary: 'Niet alle bewerkte voeding is per definitie ongezond -- het gaat vooral om hoeveel verzadigd vet, transvet, suiker en zout erin zit.', evidence_level: 'C', population: 'algemeen', context: 'voedingskwaliteit/verwerking', supported_outcomes: ['genuanceerde duiding van "bewerkt"'], limitations: ['classificatiesystemen voor "bewerking" (bv. NOVA) worden wetenschappelijk nog besproken; dit is een voorzichtige, algemene duiding'], source_ids: ['WHO-HEALTHY-DIET-2020'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['alle bewerkte voeding is ongezond', 'onbewerkt is altijd beter dan bewerkt'] },
    { claim_id: 'NK-HE-SPORTFIT-001', topic_id: 'HEALTHY_EATING', domain: 'NUTRITION', claim_text_internal: 'Sportvoeding (bv. koolhydraatgels, eiwitpoeder) kan binnen een overigens gezond, gevarieerd voedingspatroon passen; het is een aanvulling in specifieke context, geen vervanging van een gezond basispatroon.', user_friendly_summary: 'Sportvoeding zoals gels of eiwitpoeder kan prima passen binnen een verder gezond voedingspatroon -- het is een aanvulling voor specifieke situaties, geen vervanging van gewone, gevarieerde voeding.', evidence_level: 'C', population: 'sporters', context: 'sportvoeding binnen algemeen voedingspatroon', supported_outcomes: ['contextualisering van sportvoeding'], limitations: [], source_ids: ['WHO-HEALTHY-DIET-2020'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['sportvoeding vervangt gewone voeding'] },
    { claim_id: 'NK-HE-FLEX-001', topic_id: 'HEALTHY_EATING', domain: 'NUTRITION', claim_text_internal: 'Een gezond voedingspatroon vereist niet dat iedere afzonderlijke maaltijd perfect is; het patroon over dagen/weken is bepalend, wat ruimte laat voor flexibiliteit en context (cultuur, gelegenheid, voorkeur).', user_friendly_summary: 'Niet elke maaltijd hoeft perfect te zijn -- het gaat om je patroon over dagen en weken. Er is ruimte voor flexibiliteit.', evidence_level: 'C', population: 'algemeen', context: 'flexibiliteit/duurzaamheid van voedingspatroon', supported_outcomes: ['realistische, vol te houden aanpak'], limitations: [], source_ids: ['WHO-HEALTHY-DIET-2020'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['elke maaltijd moet perfect gezond zijn'] },

    // ── VOEDING VOOR TRAINING (NK-04, nieuw) ─────────────────────────────
    { claim_id: 'NK-PRE-CARB-001', topic_id: 'PRE_TRAINING', domain: 'NUTRITION', claim_text_internal: 'Voor inspanning van hogere intensiteit (>=70% VO2max) en langere duur (>90 min) wordt vaak 1-4 g/kg koolhydraten enkele uren vooraf onderzocht/aanbevolen om spier- en levergyogeen te maximaliseren.', user_friendly_summary: 'Voor een zwaardere, langere training wordt in onderzoek vaak 1-4 g koolhydraten per kg lichaamsgewicht, enkele uren vooraf, gebruikt.', evidence_level: 'A', population: 'sporters', context: 'pre-exercise voeding, hogere intensiteit/langere duur', supported_outcomes: ['glycogeenbeschikbaarheid'], limitations: ['dit is een onderzocht bereik, geen persoonlijk voorschrift -- AI/UI mag dit nooit zelf voor een gebruiker uitrekenen'], source_ids: ['ISSN-NUTRIENT-TIMING-2017'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['dit is jouw persoonlijke voorgeschreven hoeveelheid', 'AI berekent dit voor jouw gewicht'] },
    { claim_id: 'NK-PRE-FASTED-001', topic_id: 'PRE_TRAINING', domain: 'NUTRITION', claim_text_internal: 'Nuchter trainen verhoogt de acute vetoxidatie tijdens submaximale inspanning t.o.v. trainen na een koolhydraatrijke maaltijd, maar dit leidt niet automatisch tot meer netto vetverlies (dat hangt af van de totale energiebalans) en prestatie is in onderzoek vaak niet beter dan met voeding vooraf.', user_friendly_summary: 'Nuchter sporten verbrandt tijdens de training zelf iets meer vet, maar dat betekent niet automatisch dat je er ook meer vet mee kwijtraakt -- dat hangt af van je totale energiebalans over de dag. Prestatie is nuchter meestal niet beter.', evidence_level: 'A', population: 'algemeen', context: 'nuchter trainen (fasted training)', supported_outcomes: ['juiste duiding van vetoxidatie versus vetverlies'], limitations: ['acuut fysiologisch effect (vetoxidatie tijdens de sessie) is iets anders dan netto vetverlies over tijd'], source_ids: ['ISSN-NUTRIENT-TIMING-2017'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['nuchter trainen verbrandt meer vet dus geeft automatisch meer vetverlies', 'nuchter trainen is altijd beter voor vetverlies'] },
    { claim_id: 'NK-PRE-TIMING-001', topic_id: 'PRE_TRAINING', domain: 'NUTRITION', claim_text_internal: 'Hoe dichter bij het tijdstip van inspanning, hoe kleiner en beter verteerbaar een maaltijd doorgaans moet zijn om maag-darmklachten te beperken; individuele tolerantie verschilt sterk.', user_friendly_summary: 'Vlak voor het sporten kun je beter iets kleins en licht verteerbaars eten dan een grote maaltijd. Hoeveel jij precies verdraagt, verschilt van persoon tot persoon.', evidence_level: 'B', population: 'algemeen', context: 'pre-exercise voeding, timing/GI-tolerantie', supported_outcomes: ['praktisch advies GI-tolerantie'], limitations: ['individuele tolerantie sterk variabel, geen vaste tijdsdrempel gecertificeerd'], source_ids: ['ISSN-NUTRIENT-TIMING-2017'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: [] },

    // ── VOEDING TIJDENS TRAINING (NK-04, nieuw; sport-claims grotendeels hergebruik van CARB_GROUP) ──
    { claim_id: 'NK-DUR-MTC-001', topic_id: 'DURING_TRAINING', domain: 'NUTRITION', claim_text_internal: 'Bij innames boven circa 60 g/uur is een mix van meerdere koolhydraattypen (glucose+fructose, "multiple transportable carbohydrates") nodig, omdat een enkele koolhydraatbron een absorptieplafond van circa 60 g/uur heeft.', user_friendly_summary: 'Wil je meer dan zo\'n 60 gram koolhydraten per uur opnemen? Dan heb je een mix van verschillende koolhydraattypen (glucose+fructose) nodig -- één type alleen heeft een opnameplafond.', evidence_level: 'A', population: 'algemeen', context: 'koolhydraten tijdens langdurige inspanning', supported_outcomes: ['mechanisme achter hogere koolhydraatinname'], limitations: [], source_ids: ['CARB-DURING-EXERCISE-JEUKENDRUP-2014'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: [] },
    { claim_id: 'NK-DUR-RINSE-001', topic_id: 'DURING_TRAINING', domain: 'NUTRITION', claim_text_internal: 'Bij inspanning korter dan 45-75 minuten kan een koolhydraat-mondspoeling (zonder inslikken) al een prestatie-effect geven, mogelijk via signalering in mond en hersenen, zonder dat de koolhydraten daadwerkelijk als brandstof worden gebruikt.', user_friendly_summary: 'Bij kortere, intensieve inspanning kan zelfs alleen je mond spoelen met een koolhydraatdrankje (zonder doorslikken) al helpen -- vermoedelijk via een signaal naar je hersenen, niet omdat je lichaam de koolhydraten als brandstof gebruikt.', evidence_level: 'B', population: 'algemeen', context: 'korte, intensieve inspanning', supported_outcomes: ['mondspoeling-effect'], limitations: ['effect is kleiner en minder consistent dan daadwerkelijke koolhydraatinname bij langere inspanning'], source_ids: ['ISSN-NUTRIENT-TIMING-2017'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: [] },

    // ── NA TRAINING/HERSTEL (NK-04, nieuw; timing-claims grotendeels hergebruik van PROT_*) ────
    { claim_id: 'NK-POST-GLYCOGEN-001', topic_id: 'POST_TRAINING', domain: 'NUTRITION', claim_text_internal: 'Bij minder dan circa 8 uur tussen twee trainingssessies is snelle koolhydraatinname direct na afloop relevanter voor glycogeenherstel dan bij een lange hersteltijd (>24 uur), waarbij vooral de totale dagelijkse inname bepalend is.', user_friendly_summary: 'Train je twee keer op één dag met minder dan 8 uur ertussen? Dan is snel koolhydraten aanvullen na de eerste sessie belangrijker dan wanneer je pas de volgende dag weer traint -- dan telt vooral je totale dagelijkse inname.', evidence_level: 'B', population: 'sporters met meerdere sessies per dag', context: 'herstel/glycogeenaanvulling, korte turnaround', supported_outcomes: ['glycogeenherstel bij snelle turnaround'], limitations: [], source_ids: ['JEUKENDRUP-ENDURANCE-2011'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['je hebt altijd binnen 30 minuten koolhydraten nodig na training'] },
    { claim_id: 'NK-POST-TOTAL-001', topic_id: 'POST_TRAINING', domain: 'NUTRITION', claim_text_internal: 'Bij voldoende totale dagelijkse koolhydraat- en eiwitinname is het exacte tijdstip van post-workout-inname van ondergeschikt belang, behalve specifiek bij een korte hersteltijd tot de volgende sessie.', user_friendly_summary: 'Als je over de hele dag genoeg koolhydraten en eiwit binnenkrijgt, maakt het exacte moment na het sporten meestal weinig uit -- behalve als je snel weer moet trainen.', evidence_level: 'B', population: 'algemeen', context: 'herstel/timing', supported_outcomes: ['juiste duiding van "hersteltiming"'], limitations: [], source_ids: ['ISSN-NUTRIENT-TIMING-2017'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['er bestaat een strikt hersteltijdvenster van 30 minuten voor iedereen'] },

    // ── LANGDURIGE INSPANNING / KOOLHYDRAATSTRATEGIEËN (NK-04, nieuw) ───
    { claim_id: 'NK-END-LOAD-001', topic_id: 'ENDURANCE_CARB', domain: 'NUTRITION', claim_text_internal: 'Carbohydrate loading (een verhoogde koolhydraatinname van circa 7-12 g/kg/dag gedurende 24-48 uur vóór een wedstrijd van meer dan circa 90 minuten) kan de spierglycogeenvoorraad verhogen; goed getrainde sporters hebben hiervoor geen voorafgaande depletiefase nodig.', user_friendly_summary: 'Voor wedstrijden langer dan ongeveer anderhalf uur wordt "carb loading" onderzocht: een verhoogde koolhydraatinname (circa 7-12 g/kg/dag) in de 1-2 dagen ervoor. Getrainde sporters hoeven hiervoor niet eerst hun voorraad "leeg te trainen".', evidence_level: 'A', population: 'getrainde duursporters', context: 'wedstrijdvoorbereiding, inspanning >90 min', supported_outcomes: ['verhoogde spierglycogeenvoorraad'], limitations: ['dit is een onderzocht protocol, geen persoonlijk voorschrift -- niet automatisch aan te raden voor elke training'], source_ids: ['JEUKENDRUP-ENDURANCE-2011'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['carb loading is nodig voor elke training', 'AI berekent jouw persoonlijke carb-loading-schema'] },
    { claim_id: 'NK-END-LOAD-WEIGHT-001', topic_id: 'ENDURANCE_CARB', domain: 'NUTRITION', claim_text_internal: 'Carbohydrate loading kan gepaard gaan met een tijdelijke gewichtstoename doordat water samen met het extra glycogeen in de spieren wordt opgeslagen; dit is geen vetopslag.', user_friendly_summary: 'Na carb loading kun je tijdelijk iets zwaarder zijn -- dat is water dat wordt opgeslagen samen met de extra glycogeenvoorraad in je spieren, geen vet.', evidence_level: 'B', population: 'getrainde duursporters', context: 'wedstrijdvoorbereiding, gewichtseffect', supported_outcomes: ['juiste duiding van gewichtstoename bij carb loading'], limitations: [], source_ids: ['JEUKENDRUP-ENDURANCE-2011'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['carb loading laat je vet aankomen'] },
    { claim_id: 'NK-END-VLOEIBAAR-001', topic_id: 'ENDURANCE_CARB', domain: 'NUTRITION', claim_text_internal: 'Zowel vloeibare als vaste koolhydraatbronnen tijdens langdurige inspanning kunnen effectief zijn; de keuze hangt vooral af van individuele GI-tolerantie en praktische haalbaarheid tijdens het sporten.', user_friendly_summary: 'Gel, sportdrank of vast voedsel tijdens een lange inspanning kunnen allemaal werken -- wat het beste past, hangt af van wat jouw maag verdraagt en wat praktisch is tijdens het sporten.', evidence_level: 'B', population: 'algemeen', context: 'vorm van koolhydraatinname tijdens inspanning', supported_outcomes: ['praktische keuzevrijheid'], limitations: [], source_ids: ['CARB-DURING-EXERCISE-JEUKENDRUP-2014'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: [] },

    // ── SPIEROPBOUW & VOEDING (NK-04, nieuw; meeste claims hergebruik van PROT_*/CRE_*/NK-ENE-*) ──
    { claim_id: 'NK-MUS-STIMULUS-001', topic_id: 'MUSCLE_GAIN', domain: 'NUTRITION', claim_text_internal: 'Krachttraining is de primaire stimulus voor spiergroei; voeding (voldoende eiwit en energie) ondersteunt dit proces, maar vervangt de trainingsprikkel niet.', user_friendly_summary: 'Spieren groeien primair door krachttraining -- voeding ondersteunt dat proces, maar vervangt training niet.', evidence_level: 'A', population: 'algemeen', context: 'spieropbouw, basisprincipe', supported_outcomes: ['juiste prioritering training versus voeding'], limitations: [], source_ids: ['ISSN-PROTEIN-2017'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['voeding alleen (zonder training) bouwt spieren op', 'meer eiwit zonder training geeft meer spiergroei'] },
    { claim_id: 'NK-MUS-SURPLUS-001', topic_id: 'MUSCLE_GAIN', domain: 'NUTRITION', claim_text_internal: 'Voor spiermassatoename wordt in richtlijnen doorgaans een licht energieoverschot (circa 500-1000 kcal/dag boven onderhoud, hoewel dit sterk individueel varieert) aanbevolen naast voldoende eiwit en krachttraining; onder een aanhoudend energietekort is spiermassatoename beperkter.', user_friendly_summary: 'Om spiermassa op te bouwen, wordt vaak een licht calorie-overschot geadviseerd naast genoeg eiwit en krachttraining. Bij een aanhoudend calorietekort is spiergroei lastiger.', evidence_level: 'B', population: 'sporters die spiermassa willen opbouwen', context: 'spieropbouw en energiebalans', supported_outcomes: ['juiste duiding van energiebalans bij spieropbouw'], limitations: ['exacte overschot-hoeveelheid is contextafhankelijk, geen vast persoonlijk getal'], source_ids: ['DELANY-BODYCOMP-SCOPING-2025'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['AI berekent jouw persoonlijke bulk-calorieën', 'meer overschot geeft altijd meer spiergroei'] },

    // ── VETVERLIES & SPORT (NK-04, nieuw; extra voorzichtig, medische grenzen) ──
    { claim_id: 'NK-FATLOSS-RATE-001', topic_id: 'FAT_LOSS_SPORT', domain: 'NUTRITION', claim_text_internal: 'Een geleidelijk energietekort (in richtlijnen doorgaans circa 250-1000 kcal/dag) en een gematigd tempo van gewichtsverlies (circa 0,5-1,0 kg/week) worden geassocieerd met beter behoud van prestatie en vetvrije massa dan een agressief tekort.', user_friendly_summary: 'Een geleidelijk tekort en een rustig tempo van gewichtsverlies (richting 0,5-1,0 kg per week) worden in richtlijnen in verband gebracht met beter behoud van prestatie en spiermassa dan een streng, snel dieet.', evidence_level: 'B', population: 'sporters', context: 'vetverlies bij sporters', supported_outcomes: ['behoud van prestatie/vetvrije massa'], limitations: ['richtlijnen variëren, individuele context (sport, uitgangssituatie) speelt mee'], source_ids: ['DELANY-BODYCOMP-SCOPING-2025'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['AI berekent jouw persoonlijke caloriedeficit', 'sneller afvallen is altijd beter voor sporters'] },
    { claim_id: 'NK-FATLOSS-EA-001', topic_id: 'FAT_LOSS_SPORT', domain: 'NUTRITION', claim_text_internal: 'Energiebeschikbaarheid (energie-inname minus trainingsverbruik, gedeeld door vetvrije massa) onder een drempel die in richtlijnen vaak rond 30 kcal/kg vetvrije massa/dag ligt, wordt geassocieerd met verhoogd risico op RED-S.', user_friendly_summary: 'Als je, na aftrek van je trainingsverbruik, structureel te weinig energie overhoudt voor je vetvrije massa, loop je meer risico op RED-S. Richtlijnen noemen hiervoor vaak een grens rond 30 kcal per kg vetvrije massa per dag.', evidence_level: 'B', population: 'sporters', context: 'energiebeschikbaarheid/RED-S-risico', supported_outcomes: ['herkenning van risicofactor'], limitations: ['drempel is een richtlijngetal, geen exacte individuele grens; vaststelling van feitelijke energiebeschikbaarheid vereist professionele beoordeling'], source_ids: ['DELANY-BODYCOMP-SCOPING-2025', 'IOC-REDS-CONSENSUS-2023'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: ['Trainingskompas berekent jouw energiebeschikbaarheid', 'onder de drempel zitten betekent automatisch dat je RED-S hebt'] },
    { claim_id: 'NK-FATLOSS-NOCRASH-001', topic_id: 'FAT_LOSS_SPORT', domain: 'NUTRITION', claim_text_internal: 'Crashdiëten en zeer agressieve caloriebeperking worden in sportvoedingsrichtlijnen afgeraden vanwege verhoogd risico op prestatieverlies, verlies van vetvrije massa en RED-S.', user_friendly_summary: 'Crashdiëten en heel streng lijnen worden afgeraden voor sporters -- het risico op prestatieverlies, spierverlies en RED-S is groter.', evidence_level: 'B', population: 'sporters', context: 'veiligheidsgrens vetverlies', supported_outcomes: ['afraden van onveilige praktijken'], limitations: [], source_ids: ['DELANY-BODYCOMP-SCOPING-2025'], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: true, forbidden_interpretations: [] },

    // ── ARCHITECTUURREGEL (NK-04, gedeeld, HIDDEN, zelfde patroon als NK-ENE-NOCALC-001) ──
    { claim_id: 'NK-SPORTNUTR-NOCALC-001', topic_id: 'PRE_TRAINING', domain: 'NUTRITION', claim_text_internal: 'Trainingskompas berekent geen persoonlijke sportvoedingsgetallen (geen g/kg-omrekening, geen g/uur-fueling-plan, geen race-fueling-calculator, geen sweat-rate/vochtbehoefte, geen bulk/cut-calorieën); dit is architectuurbeleid, geen gebruikerszin.', user_friendly_summary: null, evidence_level: 'E', population: null, context: null, supported_outcomes: [], limitations: [], source_ids: [], last_reviewed: '2026-09-07', status: 'VERIFIED', allowed_ai_use: false, forbidden_interpretations: ['AI berekent jouw g/kg', 'AI maakt een race fueling plan voor jou', 'AI berekent jouw sweat rate/vochtbehoefte', 'AI berekent jouw bulk- of cut-calorieën'] }
  ];

  function isValidLevel(l) { return EVIDENCE_LEVELS.indexOf(l) >= 0; }
  function isValidStatus(s) { return STATUSES.indexOf(s) >= 0; }
  /* confidenceLabel: GEEN los, los-instelbaar veld per claim (dat zou
   * kunnen gaan afwijken van evidence_level/status) -- uitsluitend een
   * vaste, deterministische afleiding, exact de vier toegestane labels
   * uit sectie 4 van de opdracht. Geen schijnprecisie (geen percentages). */
  function confidenceLabel(level, status) {
    if (status === 'INSUFFICIENT' || status === 'REVISE' || status === 'REMOVE') return 'Onvoldoende bewijs';
    if (level === 'A') return 'Sterk bewijs';
    if (level === 'B') return 'Redelijk bewijs';
    if (level === 'C') return 'Contextafhankelijk';
    return 'Onvoldoende bewijs';
  }
  function allClaims() { return CLAIMS.slice(); }
  function getById(id) {
    for (var i = 0; i < CLAIMS.length; i++) if (CLAIMS[i].claim_id === id) return CLAIMS[i];
    return null;
  }
  function byTopicId(topicId) { return CLAIMS.filter(function (c) { return c.topic_id === topicId; }); }

  var NutritionKnowledgeEvidenceRegistry = {
    REGISTRY_VERSION: REGISTRY_VERSION,
    EVIDENCE_LEVELS: EVIDENCE_LEVELS,
    STATUSES: STATUSES,
    CLAIMS: CLAIMS,
    isValidLevel: isValidLevel,
    isValidStatus: isValidStatus,
    confidenceLabel: confidenceLabel,
    allClaims: allClaims,
    getById: getById,
    byTopicId: byTopicId
  };

  return NutritionKnowledgeEvidenceRegistry;
}));
